USE WAREHOUSE ENTERPRISE_WH;

CREATE DATABASE RETAIL_SCHEMAS_DW;

USE DATABASE RETAIL_SCHEMAS_DW;

CREATE SCHEMA SCHEMA_COMPARISON;

USE SCHEMA SCHEMA_COMPARISON;

CREATE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1;

CREATE STAGE RAW_STAGE
FILE_FORMAT = CSV_FORMAT;

CREATE TABLE STAR_DIM_STORE
(
STORE_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
STORE_ID NUMBER,
STORE_NAME VARCHAR,
CITY VARCHAR,
STATE VARCHAR,
REGION_NAME VARCHAR,
REGION_MANAGER VARCHAR
);


CREATE TABLE STAR_DIM_PRODUCT
(
PRODUCT_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
PRODUCT_ID NUMBER,
PRODUCT_NAME VARCHAR,
SUBCATEGORY_NAME VARCHAR,
CATEGORY_NAME VARCHAR,
UNIT_PRICE NUMBER(10,2)
);


INSERT INTO STAR_DIM_STORE(
                            STORE_ID,
                            STORE_NAME,
                            CITY,
                            STATE,
                            REGION_NAME,
                            REGION_MANAGER
)
SELECT  $1,
        $2,
        $3,
        $4,
        $5,
        $6
FROM @RAW_STAGE/stores.csv;


INSERT INTO STAR_DIM_PRODUCT(
                             PRODUCT_ID,
                             PRODUCT_NAME,
                             SUBCATEGORY_NAME,
                             CATEGORY_NAME,
                             UNIT_PRICE
)
SELECT  $1,
        $2,
        $3,
        $4,
        $5
FROM @RAW_STAGE/products.csv;


CREATE TABLE STAR_FACT_SALES
(
SALES_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
TRANSACTION_ID VARCHAR,
TRANSACTION_DATE DATE,
CUSTOMER_ID NUMBER,
STORE_KEY NUMBER REFERENCES STAR_DIM_STORE(STORE_KEY),
PRODUCT_KEY NUMBER REFERENCES STAR_DIM_PRODUCT(PRODUCT_KEY),
QUANTITY NUMBER,
TOTAL_AMOUNT NUMBER(10,2)
);


INSERT INTO STAR_FACT_SALES(TRANSACTION_ID,
                            TRANSACTION_DATE,
                            CUSTOMER_ID,
                            STORE_KEY,
                            PRODUCT_KEY,
                            QUANTITY,
                            TOTAL_AMOUNT
)
SELECT  UPD.$1,
        UPD.$2,
        UPD.$3,
        DS.STORE_KEY,
        DP.PRODUCT_KEY,
        UPD.$6,
        UPD.$6*UPD.$7
FROM @RAW_STAGE/transactions.csv AS UPD
INNER JOIN STAR_DIM_STORE DS
ON UPD.$4 = DS.STORE_ID
INNER JOIN STAR_DIM_PRODUCT DP
ON UPD.$5 = DP.PRODUCT_ID;


CREATE TABLE SNOW_DIM_REGION
(
REGION_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
REGION_NAME VARCHAR,
REGION_MANAGER VARCHAR
);


CREATE TABLE SNOW_DIM_STORE
(
STORE_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
STORE_ID NUMBER,
STORE_NAME VARCHAR,
CITY VARCHAR,
STATE VARCHAR,
REGION_KEY NUMBER REFERENCES SNOW_DIM_REGION(REGION_KEY)
);


CREATE TABLE SNOW_DIM_CATEGORY
(
CATEGORY_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
CATEGORY_NAME VARCHAR
);

CREATE TABLE SNOW_DIM_SUBCATEGORY
(
SUBCATEGORY_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
SUBCATEGORY_NAME VARCHAR,
CATEGORY_KEY NUMBER REFERENCES SNOW_DIM_CATEGORY(CATEGORY_KEY)
);

CREATE TABLE SNOW_DIM_PRODUCT
(
PRODUCT_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
PRODUCT_ID NUMBER,
PRODUCT_NAME VARCHAR,
UNIT_PRICE NUMBER(10,2),
SUBCATEGORY_KEY NUMBER REFERENCES SNOW_DIM_SUBCATEGORY(SUBCATEGORY_KEY)
);


INSERT INTO SNOW_DIM_REGION(REGION_NAME,REGION_MANAGER)
SELECT  DISTINCT $5,
        $6
FROM @RAW_STAGE/stores.csv;


INSERT INTO SNOW_DIM_STORE(STORE_ID,STORE_NAME,CITY,STATE,REGION_KEY)
SELECT  UPD.$1,
        UPD.$2,
        UPD.$3,
        UPD.$4,
        SDS.REGION_KEY
FROM @RAW_STAGE/stores.csv AS UPD
INNER JOIN SNOW_DIM_REGION AS SDS
ON UPD.$5 = SDS.REGION_NAME;


INSERT INTO SNOW_DIM_CATEGORY(CATEGORY_NAME)
SELECT DISTINCT $4
FROM @RAW_STAGE/products.csv;

INSERT INTO SNOW_DIM_SUBCATEGORY(SUBCATEGORY_NAME,CATEGORY_KEY)
SELECT  DISTINCT UPD.$3,
        SDC.CATEGORY_KEY
FROM @RAW_STAGE/products.csv AS UPD 
INNER JOIN SNOW_DIM_CATEGORY AS SDC
ON UPD.$4=SDC.CATEGORY_NAME;

INSERT INTO SNOW_DIM_PRODUCT(PRODUCT_ID,PRODUCT_NAME,UNIT_PRICE,SUBCATEGORY_KEY)
SELECT  UPD.$1,
        UPD.$2,
        UPD.$5,
        SDSC.SUBCATEGORY_KEY
FROM @RAW_STAGE/products.csv AS UPD
INNER JOIN SNOW_DIM_SUBCATEGORY AS SDSC
ON UPD.$3=SDSC.SUBCATEGORY_NAME;

CREATE TABLE SNOW_FACT_SALES
(
SALES_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
TRANSACTION_ID VARCHAR,
TRANSACTION_DATE DATE,
CUSTOMER_ID NUMBER,
STORE_KEY NUMBER REFERENCES SNOW_DIM_STORE(STORE_KEY),
PRODUCT_KEY NUMBER REFERENCES SNOW_DIM_PRODUCT(PRODUCT_KEY),
QUANTITY NUMBER,
TOTAL_AMOUNT NUMBER(10,2)
);


INSERT INTO SNOW_FACT_SALES(
                            TRANSACTION_ID,
                            TRANSACTION_DATE,
                            CUSTOMER_ID,
                            STORE_KEY,
                            PRODUCT_KEY,
                            QUANTITY,
                            TOTAL_AMOUNT
)
SELECT  UPD.$1,
        UPD.$2,
        UPD.$3,
        SDS.STORE_KEY,
        SDP.PRODUCT_KEY,
        UPD.$6,
        UPD.$6*UPD.$7
FROM @RAW_STAGE/transactions.csv AS UPD
INNER JOIN SNOW_DIM_STORE SDS
ON UPD.$4=SDS.STORE_ID
INNER JOIN SNOW_DIM_PRODUCT SDP
ON UPD.$5=SDP.PRODUCT_ID;


SELECT  SDS.REGION_NAME,
        SDP.CATEGORY_NAME,
        SUM(FS.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM STAR_DIM_STORE SDS
INNER JOIN STAR_FACT_SALES FS
ON SDS.STORE_KEY=FS.STORE_KEY
INNER JOIN STAR_DIM_PRODUCT SDP
ON SDP.PRODUCT_KEY=FS.PRODUCT_KEY
GROUP BY SDS.REGION_NAME,SDP.CATEGORY_NAME
ORDER BY TOTAL_REVENUE DESC;


SELECT  SDR.REGION_NAME,
        SDC.CATEGORY_NAME,
        SUM(FS.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SNOW_FACT_SALES FS
INNER JOIN SNOW_DIM_PRODUCT SDP
ON SDP.PRODUCT_KEY = FS.PRODUCT_KEY
INNER JOIN SNOW_DIM_SUBCATEGORY SDSC
ON SDP.SUBCATEGORY_KEY=SDSC.SUBCATEGORY_KEY
INNER JOIN SNOW_DIM_CATEGORY SDC
ON SDSC.CATEGORY_KEY=SDC.CATEGORY_KEY
INNER JOIN SNOW_DIM_STORE SDS
ON FS.STORE_KEY=SDS.STORE_KEY
INNER JOIN SNOW_DIM_REGION SDR
ON SDS.REGION_KEY=SDR.REGION_KEY
GROUP BY SDR.REGION_NAME,SDC.CATEGORY_NAME
ORDER BY TOTAL_REVENUE DESC;


SELECT  SDS.REGION_MANAGER,
        SUM(FS.QUANTITY) AS TOTAL_ITEMS_SOLD,
        SUM(FS.TOTAL_AMOUNT) AS TOTAL_SALES_AMOUNT
FROM STAR_FACT_SALES FS
INNER JOIN STAR_DIM_STORE SDS
ON FS.STORE_KEY=SDS.STORE_KEY
GROUP BY REGION_MANAGER
ORDER BY TOTAL_ITEMS_SOLD DESC,TOTAL_SALES_AMOUNT DESC;


SELECT  'Star Schema' AS SCHEMA_TYPE,
        'STAR_DIM_STORE' AS TABLE_NAME,
        COUNT(*) AS RECORD_COUNT
FROM STAR_DIM_STORE
UNION ALL
SELECT  'Star Schema' AS SCHEMA_TYPE,
        'STAR_DIM_PRODUCT' AS TABLE_NAME,
        COUNT(*) AS RECORD_COUNT
FROM STAR_DIM_PRODUCT
UNION ALL
SELECT  'Star Schema' AS SCHEMA_TYPE,
        'STAR_FACT_SALES' AS TABLE_NAME,
        COUNT(*) AS RECORD_COUNT
FROM STAR_FACT_SALES
UNION ALL
SELECT  'Snowflake Schema' AS SCHEMA_TYPE,
        'SNOW_DIM_REGION' AS TABLE_NAME,
        COUNT(*) AS RECORD_COUNT
FROM SNOW_DIM_REGION
UNION ALL
SELECT  'Snowflake Schema' AS SCHEMA_TYPE,
        'SNOW_DIM_STORE' AS TABLE_NAME,
        COUNT(*) AS RECORD_COUNT
FROM SNOW_DIM_STORE
UNION ALL
SELECT  'Snowflake Schema' AS SCHEMA_TYPE,
        'SNOW_DIM_CATEGORY' AS TABLE_NAME,
        COUNT(*) AS RECORD_COUNT
FROM SNOW_DIM_CATEGORY
UNION ALL
SELECT  'Snowflake Schema' AS SCHEMA_TYPE,
        'SNOW_DIM_SUBCATEGORY' AS TABLE_NAME,
        COUNT(*) AS RECORD_COUNT
FROM SNOW_DIM_SUBCATEGORY
UNION ALL
SELECT  'Snowflake Schema' AS SCHEMA_TYPE,
        'SNOW_DIM_PRODUCT' AS TABLE_NAME,
        COUNT(*) AS RECORD_COUNT
FROM SNOW_DIM_PRODUCT
UNION ALL
SELECT  'Snowflake Schema' AS SCHEMA_TYPE,
        'SNOW_FACT_SALES' AS TABLE_NAME,
        COUNT(*) AS RECORD_COUNT
FROM SNOW_FACT_SALES;
