CREATE DATABASE JSON_DB;

CREATE SCHEMA JSON_SCHEMA;

CREATE TABLE LAKE_RAW_EVENTS
(
RAW_EVENT VARIANT
);

CREATE FILE FORMAT JSON_FORMAT
TYPE='JSON';

CREATE STAGE JSON_STAGE
FILE_FORMAT = JSON_FORMAT;

COPY INTO LAKE_RAW_EVENTS
FROM @JSON_STAGE/batch1_events.json;

COPY INTO LAKE_RAW_EVENTS
FROM @JSON_STAGE/batch2_events.json;

CREATE OR REPLACE TABLE RAW_EVENTS_HANDLING
(
RAW_EVENT VARIANT
);

COPY INTO RAW_EVENTS_HANDLING
FROM @JSON_STAGE/invalid_events.json;

SELECT  RAW_EVENT:event_id::VARCHAR AS EVENT_ID,
        RAW_EVENT
FROM RAW_EVENTS_HANDLING;

INSERT INTO LAKE_RAW_EVENTS
SELECT RAW_EVENT
FROM RAW_EVENTS_HANDLING
WHERE RAW_EVENT:event_id::VARCHAR <> 'INVALID_JSON_PAYLOAD_MALFORMED_STRING';

SELECT COUNT(*) AS TOTAL_RAW_RECORD_CT
FROM LAKE_RAW_EVENTS;

SELECT  RAW_EVENT:event_id::VARCHAR AS EVENT_ID,
        RAW_EVENT:timestamp::TIMESTAMP AS EVENT_TIME,
        RAW_EVENT:user_id::NUMBER AS USER_ID,
        RAW_EVENT:action::VARCHAR AS ACTION,
        RAW_EVENT:order.total::NUMBER(10,2) AS ORDER_TOTAL,
        RAW_EVENT:promo_code::VARCHAR AS PROMO_CODE
FROM LAKE_RAW_EVENTS
ORDER BY EVENT_ID;

WITH NET_REVENUE AS
(
SELECT  RAW_EVENT:event_id::VARCHAR AS EVENT_ID,
        RAW_EVENT:order.total::NUMBER(10,2) AS ORDER_TOTAL,
        RAW_EVENT:order.shipping_cost::NUMBER(10,2) AS SHIPPING_COST,
        RAW_EVENT:order.tax::NUMBER(10,2) AS TAX,
        COALESCE(RAW_EVENT:discount_amount,0)::NUMBER(10,2) AS DISCOUNT_AMOUNT
FROM LAKE_RAW_EVENTS
WHERE RAW_EVENT:order.total>0
)
SELECT *,(ORDER_TOTAL-SHIPPING_COST-TAX-DISCOUNT_AMOUNT) AS NET_REVENUE
FROM NET_REVENUE
ORDER BY EVENT_ID;

WITH KPI AS
(
SELECT  COUNT(*) AS TOTAL_EVENTS,
        COUNT_IF(RAW_EVENT:order.total::NUMBER > 0 AND RAW_EVENT:action::VARCHAR ='purchase') AS TOTAL_PURCHASES,
        SUM(RAW_EVENT:order.total::NUMBER(10,2)) AS TOTAL_GROSS_REVENUE,
FROM LAKE_RAW_EVENTS
)
SELECT  TOTAL_EVENTS,
        TOTAL_PURCHASES,
        ROUND((TOTAL_PURCHASES/TOTAL_EVENTS)*100,2) AS CONVERSION_RATE_PCT,
        TOTAL_GROSS_REVENUE,
        ROUND(TOTAL_GROSS_REVENUE/TOTAL_PURCHASES,2) AS AVERAGE_ORDER_VALUE
FROM KPI;


CREATE TABLE DW_STRUCTURED_EVENTS
(
EVENT_ID VARCHAR,
EVENT_TIME TIMESTAMP,
USER_ID NUMBER,
PAGE VARCHAR,
ACTION VARCHAR,
ORDER_TOTAL NUMBER(10,2),
SHIPPING_COST NUMBER(10,2),
TAX NUMBER(10,2),
PROMO_CODE VARCHAR,
DISCOUNT_AMOUNT NUMBER(10,2),
NET_REVENUE NUMBER(10,2)
);


INSERT INTO DW_STRUCTURED_EVENTS(EVENT_ID,EVENT_TIME,USER_ID,PAGE,ACTION,ORDER_TOTAL,SHIPPING_COST,TAX,PROMO_CODE,DISCOUNT_AMOUNT,NET_REVENUE)
WITH STRUCTURED_DW AS
(
SELECT  RAW_EVENT:event_id::VARCHAR AS EVENT_ID,
        RAW_EVENT:timestamp::TIMESTAMP AS EVENT_TIME,
        RAW_EVENT:user_id::NUMBER AS USER_ID,
        RAW_EVENT:page::VARCHAR AS PAGE,
        RAW_EVENT:action::VARCHAR AS ACTION,
        RAW_EVENT:order.total::NUMBER(10,2) AS ORDER_TOTAL,
        RAW_EVENT:order.shipping_cost::NUMBER(10,2) AS SHIPPING_COST,
        RAW_EVENT:order.tax::NUMBER(10,2) AS TAX,
        RAW_EVENT:promo_code::VARCHAR AS PROMO_CODE,
        COALESCE(RAW_EVENT:discount_amount,0)::NUMBER(10,2) AS DISCOUNT_AMOUNT
FROM LAKE_RAW_EVENTS
)
SELECT  *,
        (ORDER_TOTAL-SHIPPING_COST-TAX-DISCOUNT_AMOUNT) AS NET_REVENUE
FROM STRUCTURED_DW;


SELECT  COUNT(*) AS STORED_RECORDS_QTY,
        SUM(NET_REVENUE) AS TOTAL_NET_REVENUE
FROM DW_STRUCTURED_EVENTS;

CREATE TABLE QUARANTINE_RAW_EVENTS
(
QUARANTINE_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1 ,
RAW_RECORD_TEXT VARCHAR,
REASON VARCHAR
);

INSERT INTO QUARANTINE_RAW_EVENTS(RAW_RECORD_TEXT,REASON)
SELECT  RAW_EVENT:event_id::VARCHAR,
        'MALFORMED JSON BODY'
FROM RAW_EVENTS_HANDLING
WHERE RAW_EVENT:event_id::VARCHAR = 'INVALID_JSON_PAYLOAD_MALFORMED_STRING';

