CREATE DATABASE FINANCIAL_GOVERNANCE_DB;

USE DATABASE FINANCIAL_GOVERNANCE_DB;

CREATE SCHEMA WEALTH_CORE;

USE SCHEMA WEALTH_CORE;

CREATE OR REPLACE FILE FORMAT JSON_FORMAT
TYPE = 'JSON';

CREATE OR REPLACE STAGE RAW_JSON_STAGE
FILE_FORMAT = JSON_FORMAT;

CREATE OR REPLACE FILE FORMAT RAW_TEXT_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = NONE
RECORD_DELIMITER = '\n';


CREATE TABLE BRONZE_BANK_PAYLOADS
(
INGEST_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
PAYLOAD VARIANT,
LOADED_AT TIMESTAMP
);

COPY INTO BRONZE_BANK_PAYLOADS(PAYLOAD,LOADED_AT)
FROM (
SELECT  $1,
        CURRENT_TIMESTAMP()
FROM @RAW_JSON_STAGE/batch1.json
);

COPY INTO BRONZE_BANK_PAYLOADS(PAYLOAD,LOADED_AT)
FROM (
SELECT  $1,
        CURRENT_TIMESTAMP()
FROM @RAW_JSON_STAGE/batch2.json
);

COPY INTO BRONZE_BANK_PAYLOADS(PAYLOAD,LOADED_AT)
FROM (
SELECT  $1,
        CURRENT_TIMESTAMP()
FROM @RAW_JSON_STAGE/batch3.json
)
ON_ERROR = CONTINUE;

CREATE TABLE QUARANTINE_GOVERNANCE_PAYLOADS
(
QUARANTINE_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
RAW_REASON_TEXT VARCHAR,
REASON VARCHAR
);

INSERT INTO QUARANTINE_GOVERNANCE_PAYLOADS(RAW_REASON_TEXT,REASON)
SELECT  $1,
        'MALFORMED_JSON_BODY' AS REASON
FROM @RAW_JSON_STAGE/batch3.json
( FILE_FORMAT => RAW_TEXT_FORMAT)
WHERE TRY_PARSE_JSON($1) IS NULL;


SELECT COUNT(*) AS TOTAL_BRONZE_RECORDS
FROM BRONZE_BANK_PAYLOADS;

CREATE OR REPLACE TABLE SILVER_BANK_TRANSACTIONS
(
TXN_ID VARCHAR(10),
CLIENT_ID NUMBER,
CLIENT_SSN VARCHAR(10), 
REGION VARCHAR(10),
ACCOUNT_NO VARCHAR(10),
AMOUNT NUMBER(10,2),
STATUS VARCHAR(10),
AML_RISK_SCORE VARCHAR(20)
);

INSERT INTO SILVER_BANK_TRANSACTIONS(TXN_ID,CLIENT_ID,CLIENT_SSN,REGION,ACCOUNT_NO,AMOUNT,STATUS,AML_RISK_SCORE)
SELECT  PAYLOAD:txn_id::VARCHAR(10) AS TXN_ID,
        PAYLOAD:client_id::NUMBER AS CLIENT_ID,
        PAYLOAD:client_ssn::VARCHAR(10) AS CLIENT_SSN,
        PAYLOAD:region::VARCHAR(10) AS REGION,
        PAYLOAD:account_no::VARCHAR(10) AS ACCOUNT_NO,
        PAYLOAD:amount::NUMBER(10,2) AS AMOUNT,
        PAYLOAD:status::VARCHAR(10) AS STATUS,
        PAYLOAD:aml_risk_score::VARCHAR(20) AS AML_RISK_SCORE
FROM BRONZE_BANK_PAYLOADS;

CREATE ROLE COMPLIANCE_OFFICER;

CREATE ROLE NA_ANALYST;

CREATE ROLE EU_ANALYST;

GRANT USAGE 
ON DATABASE FINANCIAL_GOVERNANCE_DB
TO ROLE COMPLIANCE_OFFICER;

GRANT USAGE 
ON SCHEMA WEALTH_CORE
TO ROLE COMPLIANCE_OFFICER;

GRANT SELECT
ON TABLE SILVER_BANK_TRANSACTIONS
TO ROLE COMPLIANCE_OFFICER;

GRANT USAGE 
ON DATABASE FINANCIAL_GOVERNANCE_DB
TO ROLE NA_ANALYST;

GRANT USAGE 
ON SCHEMA WEALTH_CORE
TO ROLE NA_ANALYST;

GRANT SELECT
ON TABLE SILVER_BANK_TRANSACTIONS
TO ROLE NA_ANALYST;

GRANT USAGE 
ON DATABASE FINANCIAL_GOVERNANCE_DB
TO ROLE EU_ANALYST;

GRANT USAGE 
ON SCHEMA WEALTH_CORE
TO ROLE EU_ANALYST;

GRANT SELECT
ON TABLE SILVER_BANK_TRANSACTIONS
TO ROLE EU_ANALYST;

SELECT COUNT(*) AS TOTAL_SILVER_RECORDS
FROM SILVER_BANK_TRANSACTIONS AS ACCOUNTADMIN;

CREATE MASKING POLICY MASK_SSN
AS 
(
CLIENT_SSN VARCHAR
)
RETURNS VARCHAR
 ->
 CASE
    WHEN CURRENT_ROLE() = 'COMPLIANCE_OFFICER'
    THEN CLIENT_SSN
    ELSE '***-**-'||RIGHT(CLIENT_SSN,4)
 END;

ALTER TABLE SILVER_BANK_TRANSACTIONS
MODIFY COLUMN CLIENT_SSN
SET MASKING POLICY MASK_SSN;

CREATE MASKING POLICY MASK_ACCOUNT
AS
(
ACCOUNT_NO VARCHAR
)
RETURNS VARCHAR
->
CASE 
    WHEN CURRENT_ROLE()='COMPLIANCE_OFFICER'
    THEN ACCOUNT_NO
    ELSE LEFT(ACCOUNT_NO,4) || '****'
END;


ALTER TABLE SILVER_BANK_TRANSACTIONS
MODIFY COLUMN ACCOUNT_NO
SET MASKING POLICY MASK_ACCOUNT;


GRANT ROLE COMPLIANCE_OFFICER
TO USER KARTHIK1808;

USE ROLE COMPLIANCE_OFFICER;

SELECT * FROM FINANCIAL_GOVERNANCE_DB.WEALTH_CORE.SILVER_BANK_TRANSACTIONS;

GRANT ROLE NA_ANALYST
TO USER KARTHIK1808;

USE ROLE NA_ANALYST;

SELECT * FROM FINANCIAL_GOVERNANCE_DB.WEALTH_CORE.SILVER_BANK_TRANSACTIONS;

GRANT ROLE EU_ANALYST
TO USER KARTHIK1808;

USE ROLE EU_ANALYST;

SELECT * FROM FINANCIAL_GOVERNANCE_DB.WEALTH_CORE.SILVER_BANK_TRANSACTIONS;

SELECT * FROM FINANCIAL_GOVERNANCE_DB.WEALTH_CORE.SILVER_BANK_TRANSACTIONS
WHERE REGION='NA';

USE ROLE ACCOUNTADMIN;

SELECT CURRENT_ROLE();

CREATE  ROW ACCESS POLICY RAP_REGION_POLICY
AS
(
REGION VARCHAR
)
RETURNS BOOLEAN
->
CASE 
    WHEN CURRENT_ROLE() = 'ACCOUNTADMIN'
    THEN TRUE
    
    WHEN CURRENT_ROLE() = 'COMPLIANCE_OFFICER'
    THEN TRUE

    WHEN CURRENT_ROLE() = 'NA_ANALYST' AND REGION ='NA'
    THEN TRUE

    WHEN CURRENT_ROLE() = 'EU_ANALYST' AND REGION = 'EU'
    THEN TRUE

    ELSE FALSE
END;

ALTER TABLE SILVER_BANK_TRANSACTIONS
ADD ROW ACCESS POLICY RAP_REGION_POLICY
ON (REGION);

USE ROLE COMPLIANCE_OFFICER;

SELECT * 
FROM SILVER_BANK_TRANSACTIONS;

USE ROLE NA_ANALYST;

SELECT * 
FROM SILVER_BANK_TRANSACTIONS;

USE ROLE EU_ANALYST;

SELECT * 
FROM SILVER_BANK_TRANSACTIONS;

USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE SECURE VIEW SECURE_GOLD_EXTERNAL_AUDIT_SUMMARY AS
SELECT  REGION,
        SUM(AMOUNT) AS TOTAL_SETTLED_VAL,
        COUNT(*) AS SETTLED_TXN_COUNT,
        ROUND(AVG(AMOUNT),2) AS AVG_SETTLED_AMOUNT
FROM SILVER_BANK_TRANSACTIONS
WHERE STATUS = 'SETTLED'
GROUP BY REGION;

SELECT * FROM SECURE_GOLD_EXTERNAL_AUDIT_SUMMARY
ORDER BY TOTAL_SETTLED_VAL DESC;

SELECT CURRENT_ROLE();

WITH BRONZE_TOTAL AS
(
SELECT  SUM(PAYLOAD:amount::NUMBER(10,2)) AS BRONZE_GROSS_TOTAL
FROM BRONZE_BANK_PAYLOADS
), SILVER_TOTAL AS       
(
SELECT SUM(AMOUNT) AS SILVER_GROSS_TOTAL
FROM SILVER_BANK_TRANSACTIONS
), GOLD_TOTAL AS
(
SELECT SUM(TOTAL_SETTLED_VAL) AS GOLD_GROSS_TOTAL
FROM SECURE_GOLD_EXTERNAL_AUDIT_SUMMARY
)
SELECT  BRONZE_GROSS_TOTAL,
        SILVER_GROSS_TOTAL,
        GOLD_GROSS_TOTAL,
        CASE 
            WHEN BRONZE_GROSS_TOTAL=SILVER_GROSS_TOTAL AND SILVER_GROSS_TOTAL> GOLD_GROSS_TOTAL
            THEN TRUE
            ELSE FALSE
        END AS RECONCILED_FLAG
FROM BRONZE_TOTAL,SILVER_TOTAL,GOLD_TOTAL;


USE ROLE NA_ANALYST;

SELECT COUNT(*) AS UNAUTHORIZED_ROWS
FROM SILVER_BANK_TRANSACTIONS
WHERE REGION <>'NA';

SELECT COUNT(*) AS UNMASKED_SSN
FROM SILVER_BANK_TRANSACTIONS
WHERE CLIENT_SSN NOT LIKE '***-**-%';

SELECT COUNT(*) AS UNMASKED_ACCOUNT
FROM SILVER_BANK_TRANSACTIONS 
WHERE ACCOUNT_NO NOT LIKE 'ACT-****';


SELECT CLIENT_ID,CLIENT_SSN,ACCOUNT_NO
FROM SILVER_BANK_TRANSACTIONS;

SELECT * 
FROM SECURE_GOLD_EXTERNAL_AUDIT_SUMMARY;

USE ROLE EU_ANALYST;

SELECT COUNT(*) AS UNAUTHORIZED_ROWS
FROM SILVER_BANK_TRANSACTIONS
WHERE REGION <> 'EU';

SELECT COUNT(*) AS UNMASKED_SSN
FROM SILVER_BANK_TRANSACTIONS
WHERE CLIENT_SSN NOT LIKE '***-**-%';

SELECT COUNT(*) AS UNMASKED_ACCOUNT
FROM SILVER_BANK_TRANSACTIONS 
WHERE ACCOUNT_NO NOT LIKE 'ACT-****';

SELECT CLIENT_ID,CLIENT_SSN,ACCOUNT_NO
FROM SILVER_BANK_TRANSACTIONS;

SELECT * 
FROM SECURE_GOLD_EXTERNAL_AUDIT_SUMMARY;

USE ROLE COMPLIANCE_OFFICER;

SELECT * 
FROM SECURE_GOLD_EXTERNAL_AUDIT_SUMMARY;