CREATE WAREHOUSE SCD_HYBRID_WH
WITH 
WAREHOUSE_SIZE = 'XSMALL'
AUTO_RESUME = TRUE
AUTO_SUSPEND = 60;

USE WAREHOUSE SCD_HYBRID_WH;

CREATE DATABASE SCD_HYBRID_DB;

USE DATABASE SCD_HYBRID_DB;

CREATE SCHEMA SCD_HYBRID_SCHEMA;

USE SCHEMA SCD_HYBRID_SCHEMA;


-- HYBRID DIMENSION TABLE
CREATE TABLE DIM_CUSTOMER_HYBRID
(
CUSTOMER_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
CUSTOMER_ID NUMBER,
CUSTOMER_NAME VARCHAR,
CITY VARCHAR,
PREVIOUS_CITY  VARCHAR,
STATE VARCHAR,
CURRENT_MEMBERSHIP VARCHAR,
PREVIOUS_MEMBERSHIP VARCHAR,
HISTORICAL_MEMBERSHIP VARCHAR,
SEGMENT VARCHAR,
EFFECTIVE_DATE DATE,
EXPIRY_DATE  DATE,
IS_CURRENT BOOLEAN
);


CREATE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1;

CREATE OR REPLACE STAGE RAW_STAGE
FILE_FORMAT = CSV_FORMAT;

INSERT INTO DIM_CUSTOMER_HYBRID(
                                CUSTOMER_ID,
                                CUSTOMER_NAME,
                                CITY,
                                PREVIOUS_CITY,
                                STATE,
                                CURRENT_MEMBERSHIP,
                                PREVIOUS_MEMBERSHIP,
                                HISTORICAL_MEMBERSHIP,
                                SEGMENT,
                                EFFECTIVE_DATE,
                                EXPIRY_DATE,
                                IS_CURRENT
)
SELECT  $1,
        $2,
        $3,
        NULL,
        $4,
        $5,
        NULL,
        $5,
        $6,
        TO_DATE('2026-01-01'),
        TO_DATE('9999-12-31'),
        TRUE
FROM @RAW_STAGE/customers_initial.csv;


SELECT  CUSTOMER_ID,
        CUSTOMER_NAME,
        CITY,
        PREVIOUS_CITY,
        STATE,
        CURRENT_MEMBERSHIP,
        PREVIOUS_MEMBERSHIP,
        HISTORICAL_MEMBERSHIP,
        SEGMENT,
        EFFECTIVE_DATE,
        EXPIRY_DATE,
        IS_CURRENT
FROM DIM_CUSTOMER_HYBRID;


UPDATE DIM_CUSTOMER_HYBRID
SET EXPIRY_DATE = DATEADD(DAY,-1,UPD.$7),
    IS_CURRENT = FALSE
FROM @RAW_STAGE/customer_updates.csv AS UPD
WHERE CUSTOMER_ID=UPD.$1 AND IS_CURRENT=TRUE;


INSERT INTO DIM_CUSTOMER_HYBRID(
                                CUSTOMER_ID,
                                CUSTOMER_NAME,
                                CITY,
                                PREVIOUS_CITY,
                                STATE,
                                CURRENT_MEMBERSHIP,
                                PREVIOUS_MEMBERSHIP,
                                HISTORICAL_MEMBERSHIP,
                                SEGMENT,
                                EFFECTIVE_DATE,
                                EXPIRY_DATE,
                                IS_CURRENT
)
SELECT  UPD.$1,
        UPD.$2,
        UPD.$3,
        HYB.CITY,
        UPD.$4,
        UPD.$5,
        HYB.CURRENT_MEMBERSHIP,
        UPD.$5,
        UPD.$6,
        UPD.$7,
        TO_DATE('9999-12-31'),
        TRUE
FROM @RAW_STAGE/customer_updates.csv AS UPD
INNER JOIN DIM_CUSTOMER_HYBRID HYB
ON UPD.$1=HYB.CUSTOMER_ID AND HYB.IS_CURRENT=FALSE;


SELECT
    customer_id,
    city,
    previous_city,
    state,
    current_membership,
    previous_membership,
    historical_membership,
    segment,
    effective_date,
    expiry_date,
    is_current
FROM DIM_CUSTOMER_HYBRID
ORDER BY customer_id, effective_date;


UPDATE DIM_CUSTOMER_HYBRID HYB
SET HYB.CITY=HYB1.CITY,
    HYB.PREVIOUS_CITY=HYB1.PREVIOUS_CITY,
    HYB.STATE=HYB1.STATE,
    HYB.CURRENT_MEMBERSHIP=HYB1.CURRENT_MEMBERSHIP,
    HYB.PREVIOUS_MEMBERSHIP=HYB1.PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_HYBRID HYB1 
WHERE HYB1.IS_CURRENT=TRUE AND 
      HYB.CUSTOMER_ID=HYB1.CUSTOMER_ID AND 
      HYB.IS_CURRENT=FALSE;

SELECT  CUSTOMER_ID,
        CUSTOMER_NAME,
        CITY,
        PREVIOUS_CITY,
        STATE,
        CURRENT_MEMBERSHIP,
        PREVIOUS_MEMBERSHIP,
        HISTORICAL_MEMBERSHIP,
        SEGMENT,
        EFFECTIVE_DATE,
        EXPIRY_DATE,
        IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID,EFFECTIVE_DATE;


SELECT  CUSTOMER_ID,
        CUSTOMER_NAME,
        CITY,
        PREVIOUS_CITY,
        STATE,
        CURRENT_MEMBERSHIP,
        PREVIOUS_MEMBERSHIP,
        SEGMENT
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT=TRUE
ORDER BY CUSTOMER_ID;


SELECT  CUSTOMER_ID,
        CUSTOMER_NAME,
        CITY,
        HISTORICAL_MEMBERSHIP,
        SEGMENT,
        EFFECTIVE_DATE,
        EXPIRY_DATE
FROM DIM_CUSTOMER_HYBRID
WHERE CUSTOMER_ID = 101 AND 
      TO_DATE('2026-03-15') BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;


SELECT COUNT(*)
FROM DIM_CUSTOMER_HYBRID;


SELECT COUNT(*)
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT=TRUE; 


SELECT COUNT(*)
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT=FALSE;