USE WAREHOUSE ENTERPRISE_WH;

CREATE DATABASE RETAIL_DW;

USE DATABASE RETAIL_DW;

CREATE SCHEMA SALES_ANALYTICS;

USE SCHEMA SALES_ANALYTICS;

CREATE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1;

CREATE STAGE RAW_STAGE
FILE_FORMAT = CSV_FORMAT;

CREATE TABLE DIM_STORE
(
STORE_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
STORE_ID NUMBER,
STORE_NAME VARCHAR,
CITY VARCHAR,
STATE VARCHAR,
STORE_MANAGER VARCHAR
);

CREATE TABLE DIM_PRODUCT
(
PRODUCT_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
PRODUCT_ID NUMBER,
PRODUCT_NAME VARCHAR,
CATEGORY VARCHAR,
UNIT_PRICE NUMBER(10,2)
);

CREATE TABLE DIM_CUSTOMER_HYBRID
(
CUSTOMER_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
CUSTOMER_ID NUMBER,
CUSTOMER_NAME VARCHAR,
CITY VARCHAR,
PREVIOUS_CITY VARCHAR,
STATE VARCHAR,
CURRENT_MEMBERSHIP VARCHAR,
PREVIOUS_MEMBERSHIP VARCHAR,
HISTORICAL_MEMBERSHIP VARCHAR,
SEGMENT VARCHAR,
EFFECTIVE_DATE DATE,
EXPIRY_DATE DATE,
IS_CURRENT BOOLEAN
);

INSERT INTO DIM_STORE(STORE_ID,STORE_NAME,CITY,STATE,STORE_MANAGER)
SELECT  $1,
        $2,
        $3,
        $4,
        $5
FROM @RAW_STAGE/stores.csv;



INSERT INTO DIM_PRODUCT(PRODUCT_ID,PRODUCT_NAME,CATEGORY,UNIT_PRICE)
SELECT  $1,
        $2,
        $3,
        $4
FROM @RAW_STAGE/products.csv;

INSERT INTO DIM_CUSTOMER_HYBRID(
                                CUSTOMER_ID,
                                CUSTOMER_NAME,
                                CITY,
                                PREVIOUS_CITY,
                                STATE,
                                CURRENT_MEMBERSHIP,
                                PREVIOUS_MEMBERSHIP,
                                HISTORICAL_MEMBERSHIP,
                                SEGMENT,
                                EFFECTIVE_DATE,
                                EXPIRY_DATE,
                                IS_CURRENT
)
SELECT  $1,
        $2,
        $3,
        NULL,
        $4,
        $5,
        NULL,
        $5,
        $6,
        TO_DATE('2026-01-01'),
        TO_DATE('9999-12-31'),
        TRUE
FROM @RAW_STAGE/customers_initial.csv;


CREATE TABLE FACT_SALES
(
SALES_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
TRANSACTION_ID VARCHAR,
TRANSACTION_DATE DATE,
CUSTOMER_KEY NUMBER REFERENCES DIM_CUSTOMER_HYBRID(CUSTOMER_KEY),
STORE_KEY NUMBER REFERENCES DIM_STORE(STORE_KEY),
PRODUCT_KEY NUMBER REFERENCES DIM_PRODUCT(PRODUCT_KEY),
QUANTITY NUMBER,
UNIT_PRICE NUMBER(10,2),
TOTAL_AMOUNT NUMBER(12,2)
);

INSERT INTO FACT_SALES(TRANSACTION_ID,TRANSACTION_DATE,CUSTOMER_KEY,STORE_KEY,PRODUCT_KEY,QUANTITY,UNIT_PRICE,TOTAL_AMOUNT) 
SELECT  'TXN-1001',
        TO_DATE('2026-02-15'),
        HYB.CUSTOMER_KEY,
        DS.STORE_KEY,
        DP.PRODUCT_KEY,
        1,
        DP.UNIT_PRICE,
        1*DP.UNIT_PRICE
FROM DIM_CUSTOMER_HYBRID HYB
CROSS JOIN DIM_STORE DS
CROSS JOIN DIM_PRODUCT DP
WHERE HYB.CUSTOMER_ID=101 AND
      DS.STORE_ID=201 AND
      DP.PRODUCT_ID = 501;


INSERT INTO FACT_SALES(TRANSACTION_ID,TRANSACTION_DATE,CUSTOMER_KEY,STORE_KEY,PRODUCT_KEY,QUANTITY,UNIT_PRICE,TOTAL_AMOUNT) 
SELECT  'TXN-1002',
        TO_DATE('2026-03-10'),
        HYB.CUSTOMER_KEY,
        DS.STORE_KEY,
        DP.PRODUCT_KEY,
        2,
        DP.UNIT_PRICE,
        2*DP.UNIT_PRICE
FROM DIM_CUSTOMER_HYBRID HYB
CROSS JOIN DIM_STORE DS
CROSS JOIN DIM_PRODUCT DP
WHERE HYB.CUSTOMER_ID=103 AND
      DS.STORE_ID=203 AND
      DP.PRODUCT_ID = 502;


UPDATE DIM_STORE
SET STORE_MANAGER = 'SURESH MENON'
WHERE STORE_ID = 201;


UPDATE DIM_CUSTOMER_HYBRID HYB
SET HYB.EXPIRY_DATE=DATEADD(DAY,-1,UPD.$7),
    HYB.IS_CURRENT=FALSE
FROM @RAW_STAGE/customer_updates.csv AS UPD
WHERE HYB.CUSTOMER_ID=UPD.$1 AND HYB.IS_CURRENT=TRUE;

INSERT INTO DIM_CUSTOMER_HYBRID(
                                CUSTOMER_ID,
                                CUSTOMER_NAME,
                                CITY,
                                PREVIOUS_CITY,
                                STATE,
                                CURRENT_MEMBERSHIP,
                                PREVIOUS_MEMBERSHIP,
                                HISTORICAL_MEMBERSHIP,
                                SEGMENT,
                                EFFECTIVE_DATE,
                                EXPIRY_DATE,
                                IS_CURRENT
)
SELECT  UPD.$1,
        UPD.$2,
        UPD.$3,
        HYB.CITY,
        UPD.$4,
        UPD.$5,
        HYB.CURRENT_MEMBERSHIP,
        UPD.$5,
        UPD.$6,
        UPD.$7,
        TO_DATE('9999-12-31'),
        TRUE
FROM @RAW_STAGE/customer_updates.csv AS UPD
INNER JOIN DIM_CUSTOMER_HYBRID HYB
ON UPD.$1=HYB.CUSTOMER_ID AND HYB.IS_CURRENT=FALSE;

UPDATE DIM_CUSTOMER_HYBRID HYB
SET HYB.CITY=HYB1.CITY,
    HYB.PREVIOUS_CITY=HYB1.PREVIOUS_CITY,
    HYB.STATE=HYB1.STATE,
    HYB.CURRENT_MEMBERSHIP=HYB1.CURRENT_MEMBERSHIP,
    HYB.PREVIOUS_MEMBERSHIP=HYB1.PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_HYBRID HYB1 
WHERE HYB1.IS_CURRENT=TRUE AND 
      HYB.CUSTOMER_ID=HYB1.CUSTOMER_ID AND 
      HYB.IS_CURRENT=FALSE;


INSERT INTO FACT_SALES(TRANSACTION_ID,TRANSACTION_DATE,CUSTOMER_KEY,STORE_KEY,PRODUCT_KEY,QUANTITY,UNIT_PRICE,TOTAL_AMOUNT) 
SELECT  'TXN-2001',
        TO_DATE('2026-04-15'),
        HYB.CUSTOMER_KEY,
        DS.STORE_KEY,
        DP.PRODUCT_KEY,
        1,
        DP.UNIT_PRICE,
        1*DP.UNIT_PRICE
FROM DIM_CUSTOMER_HYBRID HYB
CROSS JOIN DIM_STORE DS
CROSS JOIN DIM_PRODUCT DP
WHERE HYB.CUSTOMER_ID = 101 AND 
      HYB.IS_CURRENT = TRUE AND
      DS.STORE_ID = 201 AND 
      DP.PRODUCT_ID = 503;


SELECT  CUSTOMER_ID,
        CUSTOMER_NAME,
        CITY,
        PREVIOUS_CITY,
        STATE,
        CURRENT_MEMBERSHIP,
        PREVIOUS_MEMBERSHIP,
        HISTORICAL_MEMBERSHIP,
        SEGMENT,
        EFFECTIVE_DATE,
        EXPIRY_DATE,
        IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID,EFFECTIVE_DATE;


SELECT  FS.TRANSACTION_ID,
        FS.TRANSACTION_DATE,
        HYB.CUSTOMER_ID,
        HYB.CUSTOMER_NAME,
        HYB.CITY AS CURRENT_CITY,
        HYB.HISTORICAL_MEMBERSHIP AS MEMBERSHIP_AT_PURCHASE,
        HYB.SEGMENT AS SEGMENT_AT_PURCHASE,
        DS.STORE_NAME,
        DP.PRODUCT_NAME,
        FS.TOTAL_AMOUNT 
FROM FACT_SALES FS
INNER JOIN DIM_CUSTOMER_HYBRID HYB
ON FS.CUSTOMER_KEY=HYB.CUSTOMER_KEY
INNER JOIN DIM_STORE DS
ON FS.STORE_KEY= DS.STORE_KEY
INNER JOIN DIM_PRODUCT DP
ON FS.PRODUCT_KEY=DP.PRODUCT_KEY
WHERE HYB.CUSTOMER_ID=101;
        


SELECT 'STORE DIMENSION RECORDS' AS METRIC, COUNT(*) AS VALUE
FROM DIM_STORE
UNION ALL
SELECT 'PRODUCT DIMENSION RECORDS' AS METRIC, COUNT(*) AS VALUE
FROM DIM_PRODUCT
UNION ALL
SELECT 'TOTAL CUSTOMER DIMENSION RECORDS' AS METRIC, COUNT(*) AS VALUE
FROM DIM_CUSTOMER_HYBRID
UNION ALL
SELECT 'CURRENT CUSTOMER RECORDS' AS METRIC, COUNT(*) AS VALUE
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = TRUE
UNION ALL
SELECT 'HISTORICAL CUSTOMER RECORDS' AS METRIC, COUNT(*) AS VALUE
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = FALSE
UNION ALL
SELECT 'FACT SALES TRANSACTIONS' AS METRIC, COUNT(*) AS VALUE
FROM FACT_SALES;