CREATE DATABASE CLEANROOM_SHARED_DB;

USE DATABASE CLEANROOM_SHARED_DB;

CREATE SCHEMA PARTNER_TELEMETRY;

USE SCHEMA PARTNER_TELEMETRY;

CREATE OR REPLACE FILE FORMAT JSON_FORMAT
TYPE = 'JSON';

CREATE OR REPLACE STAGE JSON_STAGE
FILE_FORMAT = JSON_FORMAT;

CREATE TABLE BRONZE_RETAIL_TRANSACTIONS
(
POS_DATA VARIANT
);

CREATE TABLE BRONZE_AD_EXPOSURES
(
EXPOSURE_DATA VARIANT
);

COPY INTO BRONZE_RETAIL_TRANSACTIONS
FROM @JSON_STAGE/RAW_RETAIL_TRANSACTIONS.json;

COPY INTO BRONZE_AD_EXPOSURES
FROM @JSON_STAGE/RAW_AD_EXPOSURES.json;

SELECT COUNT(*) AS TOTAL_RETAIL_RECORDS
FROM BRONZE_RETAIL_TRANSACTIONS;

CREATE OR REPLACE TABLE SILVER_ATTRIBUTION_MATCH
(
POS_ID VARCHAR(20),
STORE_ID VARCHAR(20),
CAMPAIGN_NAME VARCHAR(20),
CHANNEL VARCHAR(20),
BASKET_VALUE NUMBER(10,2),
CONVERSION_HOURS NUMBER
);

INSERT INTO SILVER_ATTRIBUTION_MATCH(POS_ID,STORE_ID,CAMPAIGN_NAME,CHANNEL,BASKET_VALUE,CONVERSION_HOURS)
SELECT  POS.POS_DATA:pos_id::VARCHAR(20) AS POS_ID,
        POS.POS_DATA:store_id::VARCHAR(20) AS STORE_ID,
        AD.EXPOSURE_DATA:campaign_name::VARCHAR(20) AS CAMPAIGN_NAME,
        AD.EXPOSURE_DATA:channel::VARCHAR(20) AS CHANNEL,
        POS.POS_DATA:basket_value::NUMBER(10,2) AS BASKET_VALUE,
        DATEDIFF('HOUR',AD.EXPOSURE_DATA:timestamp::TIMESTAMP,POS.POS_DATA:timestamp::TIMESTAMP) AS CONVERSION_HOURS
FROM BRONZE_RETAIL_TRANSACTIONS POS
INNER JOIN BRONZE_AD_EXPOSURES AD
ON POS.POS_DATA:hashed_email::VARCHAR(20)=AD.EXPOSURE_DATA:hashed_email::VARCHAR(20);

SELECT * FROM SILVER_ATTRIBUTION_MATCH;

CREATE SECURE VIEW SECURE_GOLD_CAMPAIGN_ATTRIBUTION_PERFORMANCE AS
SELECT  CAMPAIGN_NAME,
        CHANNEL,
        COUNT(DISTINCT POS_ID) AS CONVERTED_USER_COUNT,
        SUM(BASKET_VALUE) AS TOTAL_ATTRIBUTED_VAL,
        AVG(BASKET_VALUE) AS AVG_BASKET_VALUE
FROM SILVER_ATTRIBUTION_MATCH
GROUP BY CAMPAIGN_NAME,CHANNEL
HAVING COUNT(DISTINCT POS_ID)>=2;

SELECT * FROM SECURE_GOLD_CAMPAIGN_ATTRIBUTION_PERFORMANCE;

USE ROLE ACCOUNTADMIN;

CREATE SHARE SHARE_CPG_PARTNER_ANALYTICS;

GRANT USAGE
ON DATABASE CLEANROOM_SHARED_DB
TO SHARE SHARE_CPG_PARTNER_ANALYTICS;

GRANT USAGE 
ON SCHEMA PARTNER_TELEMETRY
TO SHARE SHARE_CPG_PARTNER_ANALYTICS;

GRANT SELECT 
ON VIEW SECURE_GOLD_CAMPAIGN_ATTRIBUTION_PERFORMANCE
TO SHARE SHARE_CPG_PARTNER_ANALYTICS;

SHOW SHARES LIKE 'SHARE_CPG_PARTNER_ANALYTICS'; 

CREATE MANAGED ACCOUNT CPG_READER_ACCT_01
ADMIN_NAME = 'READER_ADMIN'
ADMIN_PASSWORD = 'Password1234567890'
TYPE = READER;

ALTER SHARE SHARE_CPG_PARTNER_ANALYTICS
ADD ACCOUNTS = RXMYIMN.CPG_READER_ACCT_01;

SHOW MANAGED ACCOUNTS;

SELECT
    COUNT(*) AS SILVER_MATCHED_RECORDS,
    SUM(BASKET_VALUE) AS SILVER_TOTAL_SALES
FROM SILVER_ATTRIBUTION_MATCH;

SELECT
    COUNT(*) AS GOLD_GROUP_COUNT,
    SUM(TOTAL_ATTRIBUTED_VAL) AS GOLD_TOTAL_SALES
FROM SECURE_GOLD_CAMPAIGN_ATTRIBUTION_PERFORMANCE;



