USE WAREHOUSE SNOWFLAKE_LEARNING_WH;

USE DATABASE SNOWFLAKE_PROJECTS_DB;

USE SCHEMA SNOWFLAKE_PROJECTS_SCHEMA;

CREATE FILE FORMAT JSON_FORMAT
TYPE = 'JSON';

CREATE STAGE PRO_20B_STG
FILE_FORMAT = JSON_FORMAT;


CREATE TABLE STG_RATINGS
(
RATING_ID VARCHAR(20),
AGENCY VARCHAR(20),
CREDIT_SCORE_BAND VARCHAR(20),
RISK_TIER VARCHAR(20)
);

INSERT INTO STG_RATINGS(RATING_ID,
                        AGENCY,
                        CREDIT_SCORE_BAND,
                        RISK_TIER)
SELECT  VALUE:rating_id::VARCHAR(20) AS RATING_ID,
        VALUE:agency::VARCHAR(20) AS AGENCY,
        VALUE:credit_score_band::VARCHAR(20) AS CREDIT_SCORE_BAND,
        VALUE: risk_tier::VARCHAR(20) AS RISK_TIER
FROM @PRO_20B_STG/raw_ratings.json,
LATERAL FLATTEN(INPUT => $1);

CREATE TABLE STG_BRANCHES
(
BRANCH_ID VARCHAR(20),
BRANCH_NAME VARCHAR(20),
REGION VARCHAR(20)
);

INSERT INTO STG_BRANCHES(BRANCH_ID,
                        BRANCH_NAME,
                        REGION)
SELECT  VALUE:branch_id::VARCHAR(20) AS BRANCH_ID,
        VALUE:branch_name::VARCHAR(20) AS BRANCH_NAME,
        VALUE:region::VARCHAR(20) AS REGION
FROM @PRO_20B_STG/raw_branches.json,
LATERAL FLATTEN(INPUT => $1);

SELECT  'STG_RATINGS' AS STAGING_TABLE,
        COUNT(*) AS RECORD_COUNT
FROM STG_RATINGS
UNION ALL
SELECT  'STG_BRANCHES',
        COUNT(*)
FROM STG_BRANCHES;

CREATE TABLE FACT_CUSTOMER_FACILITY_ELIGIBILITY
(
CUSTOMER_ID VARCHAR(20),
FACILITY_ID VARCHAR(20),
ELIGIBILITY_FLAG BOOLEAN
);

INSERT INTO FACT_CUSTOMER_FACILITY_ELIGIBILITY(CUSTOMER_ID,
                                               FACILITY_ID,
                                               ELIGIBILITY_FLAG)
SELECT  VALUE:customer_id::VARCHAR(20) AS CUSTOMER_ID,
        VALUE:facility_id::VARCHAR(20) AS FACILITY_ID,
        VALUE:eligibility_flag::BOOLEAN AS ELIGIBILITY_FLAG
FROM @PRO_20B_STG/raw_facilities.json,
LATERAL FLATTEN(INPUT => $1);

SELECT * FROM FACT_CUSTOMER_FACILITY_ELIGIBILITY;


CREATE TABLE FACT_LOAN_APPLICATION_SNAPSHOT
(
APP_ID VARCHAR(20),
CUSTOMER_ID VARCHAR(20),
SUBMITTED_DATE DATE,
UNDERWRITTEN_DATE DATE,
APPROVED_DATE DATE,
DISBURSED_DATE DATE,
LOAN_AMOUNT DECIMAL(10,2)
);

INSERT INTO FACT_LOAN_APPLICATION_SNAPSHOT(APP_ID,
                                           CUSTOMER_ID,
                                           SUBMITTED_DATE,                                                                            UNDERWRITTEN_DATE,
                                           APPROVED_DATE,
                                           DISBURSED_DATE,
                                           LOAN_AMOUNT)
SELECT  VALUE:app_id::VARCHAR(20) AS APP_ID,
        VALUE:customer_id::VARCHAR(20) AS CUSTOMER_ID,
        VALUE:submitted_date::DATE AS SUBMITTED_DATE,
        VALUE:underwritten_date::DATE AS UNDERWRITTEN_DATE,
        VALUE:approved_date::DATE AS APPROVED_DATE,
        VALUE:disbursed_date::DATE AS DISBURSED_DATE,
        VALUE:loan_amount::DECIMAL(10,2) AS LOAN_AMOUNT
FROM @PRO_20B_STG/raw_loan_applications.json,
LATERAL FLATTEN(INPUT => $1);

SELECT * FROM FACT_LOAN_APPLICATION_SNAPSHOT;

CREATE TABLE CDC_LOAN_UPDATES
(
APP_ID VARCHAR(20),
APPROVED_DATE DATE,
DISBURSED_DATE DATE
);

INSERT INTO CDC_LOAN_UPDATES(APP_ID,
                             APPROVED_DATE,
                             DISBURSED_DATE)
SELECT  VALUE:app_id::VARCHAR(20) AS APP_ID,
        VALUE:approved_date::DATE AS APPROVED_DATE,
        VALUE:disbursed_date::DATE AS DISBURSED_DATE
FROM @PRO_20B_STG/cdc_loan_updates.json,
LATERAL FLATTEN(INPUT => $1);

SELECT * FROM CDC_LOAN_UPDATES;

MERGE INTO FACT_LOAN_APPLICATION_SNAPSHOT AS T
USING CDC_LOAN_UPDATES AS S
ON T.APP_ID = S.APP_ID
WHEN MATCHED THEN 
    UPDATE 
        SET T.APPROVED_DATE = S.APPROVED_DATE,
            T.DISBURSED_DATE = S.DISBURSED_DATE
WHEN NOT MATCHED THEN
    INSERT(APP_ID,APPROVED_DATE,DISBURSED_DATE)
    VALUES(S.APP_ID,S.APPROVED_DATE,S.DISBURSED_DATE);

SELECT * FROM FACT_LOAN_APPLICATION_SNAPSHOT
WHERE APP_ID = 'APP-9001';

SELECT  'DATE_SEQUENCE_CHK' AS CHECK_NAME,
        COUNT(*) AS INVALID_SEQUENCES,
        CASE WHEN COUNT(*) = 0 THEN 'PASSED'
        ELSE 'FAILED'
        END AS STATUS
FROM FACT_LOAN_APPLICATION_SNAPSHOT
WHERE SUBMITTED_DATE IS NOT NULL
AND UNDERWRITTEN_DATE IS NOT NULL
AND (
UNDERWRITTEN_DATE < SUBMITTED_DATE
OR (APPROVED_DATE IS NOT NULL
AND APPROVED_DATE < UNDERWRITTEN_DATE)
OR (DISBURSED_DATE IS NOT NULL
AND APPROVED_DATE IS NOT NULL
AND DISBURSED_DATE < APPROVED_DATE)
);

SELECT  APP_ID,
        APPROVED_DATE,
        DISBURSED_DATE
FROM FACT_LOAN_APPLICATION_SNAPSHOT
BEFORE(STATEMENT => '01c6ccf8-0204-8e7c-0005-247e00043456')
WHERE APP_ID='APP-9001';

ALTER TABLE FACT_CUSTOMER_FACILITY_ELIGIBILITY
CLUSTER BY (CUSTOMER_ID,FACILITY_ID);

SHOW TABLES LIKE 'FACT_CUSTOMER_FACILITY_ELIGIBILITY';

