USE WAREHOUSE SNOWFLAKE_LEARNING_WH;

USE DATABASE SNOWFLAKE_PROJECTS_DB;

USE SCHEMA SNOWFLAKE_PROJECTS_SCHEMA;

CREATE STAGE PRO_21C_STG
FILE_FORMAT = JSON_FORMAT;

CREATE TABLE IF NOT EXISTS raw_po_stg 
(
po_id VARCHAR(50) PRIMARY KEY,
supplier_id VARCHAR(50), 
amount_local DECIMAL(15, 2), 
currency VARCHAR(10), 
po_date DATE 
);

CREATE TABLE IF NOT EXISTS raw_fx_rates_stg 
(
currency VARCHAR(10),
fx_to_usd DECIMAL(10, 6),
effective_date DATE 
);

CREATE TABLE IF NOT EXISTS cdc_fx_updates_stg 
(
currency VARCHAR(10),
fx_to_usd DECIMAL(10, 6),
effective_date DATE
);

CREATE TABLE IF NOT EXISTS DIM_CURRENCY_CONFORMED 
(
currency_sk VARCHAR(50) PRIMARY KEY,
currency VARCHAR(10),
fx_to_usd DECIMAL(10, 6),
effective_date DATE 
);

CREATE TABLE IF NOT EXISTS FACT_GLOBAL_PROCUREMENT 
(
po_id VARCHAR(50) PRIMARY KEY,
supplier_id VARCHAR(50),
currency_sk VARCHAR(50),
currency VARCHAR(10),
amount_local DECIMAL(15, 2),
amount_usd DECIMAL(15, 2)
);

INSERT INTO DIM_CURRENCY_CONFORMED 
VALUES 
('CURR_EUR_01', 'EUR', 1.0850, '2026-08-10'),
('CURR_JPY_01', 'JPY', 0.0067, '2026-08-12');

INSERT INTO raw_po_stg 
VALUES 
('PO-9001', 'SUP-77', 150000.00, 'EUR', '2026-08-10'), 
('PO-9002', 'SUP-88', 2500000.00, 'JPY', '2026-08-12');

INSERT INTO raw_fx_rates_stg
VALUES 
('EUR', 1.0850, '2026-08-10'), 
('JPY', 0.0067, '2026-08-12');

INSERT INTO cdc_fx_updates_stg 
VALUES 
('EUR', 1.0910, '2026-08-10');

SELECT  'RAW_PO' AS SOURCE_STREAM,
        COUNT(*) AS RECORDS_PASSED
FROM raw_po_stg
UNION ALL 
SELECT  'RAW_FX',
        COUNT(*)
FROM raw_fx_rates_stg;

CREATE TABLE IF NOT EXISTS DIM_SUPPLIER
(
SUPPLIER_SK NUMBER PRIMARY KEY AUTOINCREMENT,
SUPPLIER_ID VARCHAR(38)
);

INSERT INTO DIM_SUPPLIER (SUPPLIER_ID)
SELECT DISTINCT SUPPLIER_ID
FROM raw_po_stg
ORDER BY SUPPLIER_ID;

SELECT * FROM DIM_SUPPLIER;

SELECT 'Global Procurement' AS BUSINESS_PROCESS,
'YES' AS CONFORMED_SUPPLIER,
'YES' AS CONFORMED_CURRENCY,
'USD Equivalent' AS BASE_CURRENCY_GRAIN

UNION ALL

SELECT 'Customs & Tariffs',
'YES',
'YES',
'USD Equivalent';

INSERT INTO FACT_GLOBAL_PROCUREMENT(PO_ID,SUPPLIER_ID, CURRENCY_SK,CURRENCY, AMOUNT_LOCAL, AMOUNT_USD)
SELECT
PO.PO_ID,
PO.SUPPLIER_ID,
CUR.CURRENCY_SK,
CUR.CURRENCY,
PO.AMOUNT_LOCAL,
ROUND(PO.AMOUNT_LOCAL * CUR.FX_TO_USD, 2) AS AMOUNT_USD
FROM raw_po_stg PO
JOIN DIM_CURRENCY_CONFORMED CUR
ON PO.CURRENCY = CUR.CURRENCY;

SELECT * FROM FACT_GLOBAL_PROCUREMENT;

CREATE VIEW VW_CROSS_MART AS
SELECT  PO_ID,
        SUPPLIER_ID,
        CURRENCY,
        AMOUNT_LOCAL,
        AMOUNT_USD,
        'MATCHED' AS RECOND_STATUS
FROM FACT_GLOBAL_PROCUREMENT;

SELECT * FROM VW_CROSS_MART;

MERGE INTO DIM_CURRENCY_CONFORMED T
USING cdc_fx_updates_stg S
ON T.CURRENCY = S.CURRENCY
WHEN MATCHED THEN
    UPDATE
        SET T.FX_TO_USD = S.FX_TO_USD,
            T.EFFECTIVE_DATE = S.EFFECTIVE_DATE
WHEN NOT MATCHED THEN
    INSERT(CURRENCY_SK, CURRENCY,FX_TO_USD, EFFECTIVE_DATE)
    VALUES(CONCAT('CURR_',S.CURRENCY,'_01'), S.CURRENCY, S.FX_TO_USD, S.EFFECTIVE_DATE);

UPDATE FACT_GLOBAL_PROCUREMENT F
SET AMOUNT_USD = ROUND(F.AMOUNT_LOCAL * D.FX_TO_USD, 2)
FROM DIM_CURRENCY_CONFORMED D
WHERE F.CURRENCY = D.CURRENCY
AND F.PO_ID = 'PO-9001';

SELECT * FROM FACT_GLOBAL_PROCUREMENT;

SELECT
'FX_VARIANCE_TOLERANCE' AS AUDIT_CHECK,
CONCAT(
ROUND(
COALESCE(
SUM(ABS(F.AMOUNT_USD - ROUND(F.AMOUNT_LOCAL * D.FX_TO_USD, 2)))
/ NULLIF(SUM(F.AMOUNT_USD), 0) * 100,
0
),
2
),
'%'
) AS VARIANCE_DETECTED,
CASE
WHEN COALESCE(
SUM(ABS(F.AMOUNT_USD - ROUND(F.AMOUNT_LOCAL * D.FX_TO_USD, 2)))
/ NULLIF(SUM(F.AMOUNT_USD), 0) * 100,
0
) <= 0.01
THEN 'PASSED'
ELSE 'FAILED'
END AS STATUS
FROM FACT_GLOBAL_PROCUREMENT F
JOIN DIM_CURRENCY_CONFORMED D
ON F.CURRENCY = D.CURRENCY;


WITH PRE_MERGE AS
(
SELECT  PO.PO_ID,
        ROUND((PO.AMOUNT_LOCAL*DIM.FX_TO_USD),2) AS PRE_MERGE_USD
FROM RAW_PO_STG PO
JOIN DIM_CURRENCY_CONFORMED 
BEFORE (STATEMENT => '01c6cde4-0204-8e7c-0005-247e00047896') DIM
ON PO.CURRENCY = DIM.CURRENCY
WHERE PO.PO_ID='PO-9001'
),
POST_MERGE AS
(
SELECT  PO.PO_ID,
        ROUND((PO.AMOUNT_LOCAL*DIM.FX_TO_USD),2) AS POST_MERGE_USD
FROM RAW_PO_STG PO
JOIN DIM_CURRENCY_CONFORMED DIM
ON PO.CURRENCY = DIM.CURRENCY
WHERE PO.PO_ID='PO-9001'
)
SELECT PRE.PO_ID,PRE_MERGE_USD, POST_MERGE_USD 
FROM PRE_MERGE PRE,POST_MERGE POST
WHERE PRE.PO_ID = POST.PO_ID;

ALTER TABLE FACT_GLOBAL_PROCUREMENT
CLUSTER BY (CURRENCY_SK,SUPPLIER_ID);

SHOW TABLES LIKE 'FACT_GLOBAL_PROCUREMENT';