CREATE DATABASE LAKEHOUSE_DB;

CREATE SCHEMA LAKEHOUSE_SCHEMA;

CREATE FILE FORMAT JSON_FORMAT
TYPE='JSON';

CREATE STAGE RAW_JSON_STAGE
FILE_FORMAT = JSON_FORMAT;

CREATE TABLE BRONZE_PAYMENT_PAYLOADS
(
RAW_PAYLOADS VARIANT
);

COPY INTO BRONZE_PAYMENT_PAYLOADS
FROM @RAW_JSON_STAGE/raw_payment_gateway_payloads.json;

SELECT  COUNT(*) AS TOTAL_BRONZE_RECORDS_CT
FROM BRONZE_PAYMENT_PAYLOADS;

CREATE TABLE SILVER_CLEANED_TRANSACTIONS
(
TXN_ID VARCHAR(20),
TXN_TIME TIMESTAMP,
MERCHANT_ID NUMBER,
MERCHANT_NAME VARCHAR(20),
MASKED_CARD VARCHAR(20),
GROSS NUMBER(12,2),
PROCESSING_FEE NUMBER(10,2),
NET_SETTLEMENT_AMOUNT NUMBER(10,2),
STATUS VARCHAR(20)
);

INSERT INTO SILVER_CLEANED_TRANSACTIONS(TXN_ID,TXN_TIME,MERCHANT_ID,MERCHANT_NAME,MASKED_CARD,GROSS,PROCESSING_FEE,NET_SETTLEMENT_AMOUNT,STATUS)
WITH SILVER_TRANS AS
(
SELECT  RAW_PAYLOADS:txn_id::VARCHAR(20) AS TXN_ID,
        RAW_PAYLOADS:txn_time::TIMESTAMP AS TXN_TIME,
        RAW_PAYLOADS:merchant_id::NUMBER AS MERCHANT_ID,
        RAW_PAYLOADS:merchant_name::VARCHAR(20) AS MERCHANT_NAME,
        CONCAT('XXXX-XXXX-XXXX-',RIGHT(RAW_PAYLOADS:card_number::VARCHAR(20),4)) AS MASKED_CARD,
        RAW_PAYLOADS:amount::NUMBER(12,2) AS GROSS,
        ROUND((RAW_PAYLOADS:amount::NUMBER(12,2)*RAW_PAYLOADS:fee_pct::NUMBER(10,1))/100,2) AS PROCESSING_FEE,
        RAW_PAYLOADS:status::VARCHAR(20) AS STATUS
FROM BRONZE_PAYMENT_PAYLOADS
)
SELECT  TXN_ID,
        TXN_TIME,
        MERCHANT_ID,
        MERCHANT_NAME,
        MASKED_CARD,
        GROSS,
        PROCESSING_FEE,
        ROUND((GROSS-PROCESSING_FEE),2) AS NET_SETTLEMENT_AMOUNT,
        STATUS
FROM SILVER_TRANS;


SELECT  TXN_ID,
        MERCHANT_ID,
        MERCHANT_NAME,
        MASKED_CARD,
        GROSS,
        PROCESSING_FEE,
        NET_SETTLEMENT_AMOUNT,
        STATUS
FROM SILVER_CLEANED_TRANSACTIONS;


CREATE TABLE GOLD_MERCHANT_SETTLEMENTS
(
MERCHANT_ID NUMBER,
MERCHANT_NAME VARCHAR(20),
TOTAL_APPROVED_GROSS NUMBER(10,2),
TOTAL_GATEWAY_FEES NUMBER(10,2),
TOTAL_NET_PAYOUT NUMBER(10,2),
APPROVED_COUNT NUMBER
);

INSERT INTO GOLD_MERCHANT_SETTLEMENTS(MERCHANT_ID,MERCHANT_NAME,TOTAL_APPROVED_GROSS,TOTAL_GATEWAY_FEES,TOTAL_NET_PAYOUT,APPROVED_COUNT)
SELECT  MERCHANT_ID,
        MERCHANT_NAME,
        SUM(GROSS) AS TOTAL_APPROVED_GROSS,
        SUM(PROCESSING_FEE) AS TOTAL_GATEWAY_FEES,
        SUM(NET_SETTLEMENT_AMOUNT) AS TOTAL_NET_PAYOUT,
        COUNT(STATUS) AS APPROVED_COUNT
FROM SILVER_CLEANED_TRANSACTIONS
WHERE STATUS = 'APPROVED'
GROUP BY MERCHANT_ID,MERCHANT_NAME;

SELECT  MERCHANT_ID,
        MERCHANT_NAME,
        TOTAL_APPROVED_GROSS,
        TOTAL_GATEWAY_FEES,
        TOTAL_NET_PAYOUT,
        APPROVED_COUNT
FROM GOLD_MERCHANT_SETTLEMENTS
ORDER BY MERCHANT_ID;

SELECT  TXN_ID,
        MERCHANT_NAME,
        GROSS,
        STATUS
FROM SILVER_CLEANED_TRANSACTIONS
WHERE MERCHANT_NAME = 'TechZone';

UPDATE SILVER_CLEANED_TRANSACTIONS
SET STATUS = 'REFUNDED'
WHERE MERCHANT_NAME = 'TechZone' AND STATUS = 'APPROVED';

SELECT  TXN_ID,
        MERCHANT_NAME,
        GROSS,
        STATUS
FROM SILVER_CLEANED_TRANSACTIONS
WHERE MERCHANT_NAME = 'TechZone';

SELECT  TXN_ID,
        MERCHANT_NAME,
        GROSS,
        STATUS
FROM SILVER_CLEANED_TRANSACTIONS
BEFORE(STATEMENT => '01c69615-3203-3254-0017-d5ea00176f1a')
WHERE MERCHANT_NAME = 'TechZone'
ORDER BY TXN_ID;

UPDATE SILVER_CLEANED_TRANSACTIONS AS CURRENT_TAB
SET CURRENT_TAB.STATUS = HISTORICAL.STATUS 
FROM 
(SELECT TXN_ID,
        MERCHANT_NAME,
        GROSS,
        STATUS
FROM SILVER_CLEANED_TRANSACTIONS
BEFORE(STATEMENT => '01c69615-3203-3254-0017-d5ea00176f1a')
WHERE MERCHANT_NAME = 'TechZone'
ORDER BY TXN_ID
) AS HISTORICAL
WHERE CURRENT_TAB.TXN_ID=HISTORICAL.TXN_ID;


SELECT  MERCHANT_NAME,
        COUNT_IF(STATUS='APPROVED') AS APPROVED_STATUS,
        COUNT_IF(STATUS='REFUNDED') AS REFUNDED_STATUS
FROM SILVER_CLEANED_TRANSACTIONS
WHERE MERCHANT_NAME='TechZone'
GROUP BY MERCHANT_NAME;

WITH BRONZE_SUM AS
(
SELECT  SUM(RAW_PAYLOADS:amount::NUMBER(10,2)) AS BRONZE_GROSS_SUM
FROM BRONZE_PAYMENT_PAYLOADS
),SILVER_SUM AS
(
SELECT  SUM(GROSS) AS SILVER_GROSS_SUM
FROM SILVER_CLEANED_TRANSACTIONS
),GOLD_SUM AS
(
SELECT  SUM(TOTAL_APPROVED_GROSS) AS GOLD_GROSS_SUM
FROM GOLD_MERCHANT_SETTLEMENTS
)
SELECT  BRONZE_GROSS_SUM,
        SILVER_GROSS_SUM,
        GOLD_GROSS_SUM,
        CASE 
            WHEN BRONZE_GROSS_SUM=SILVER_GROSS_SUM
            THEN TRUE 
            ELSE FALSE
        END AS DATA_MATCH_FLAG
FROM BRONZE_SUM,SILVER_SUM,GOLD_SUM;
        
