-- TASK 1
CREATE WAREHOUSE SALES_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

-- TASK 2
CREATE DATABASE CUSTOMER_SALES_DB;

-- TASK 3
CREATE SCHEMA SALES_SCHEMA;

-- TASK 4
USE WAREHOUSE SALES_WH;
USE DATABASE CUSTOMER_SALES_DB;
USE SCHEMA SALES_SCHEMA;

-- TASK 5
CREATE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1;

-- TASK 6
CREATE STAGE SALES_STAGE
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);


-- QUERYING 
SHOW FILE FORMATS;
SHOW STAGES;
LIST @SALES_STAGE;

-- RAW TABLES TASK 8
CREATE TABLE RAW_CUSTOMERS
(
customer_id NUMBER ,
first_name VARCHAR ,
last_name VARCHAR ,
email VARCHAR ,
phone VARCHAR ,
address VARCHAR 
);

CREATE TABLE RAW_FOODITEMS
(
food_id NUMBER ,
name VARCHAR ,
price NUMBER(10,2) ,
category VARCHAR ,
availability VARCHAR
);

CREATE TABLE RAW_ORDERS
(
order_id NUMBER ,
customer_id NUMBER ,
food_id NUMBER ,
quantity NUMBER,
order_date TIMESTAMP ,
status VARCHAR ,
total_amount NUMBER(10,2)
);

-- TASK 9
COPY INTO RAW_CUSTOMERS
FROM @SALES_STAGE/customers.csv;

COPY INTO RAW_FOODITEMS
FROM @SALES_STAGE/fooditems.csv;

COPY INTO RAW_ORDERS
FROM @SALES_STAGE/orders.csv;

-- STAGING TABLES (VALIDATION TABLES)
CREATE TABLE CUSTOMERS
(
customer_id NUMBER PRIMARY KEY,
first_name VARCHAR NOT NULL,
last_name VARCHAR ,
email VARCHAR NOT NULL UNIQUE,
phone VARCHAR NOT NULL,
address VARCHAR 
);

CREATE TABLE FOODITEMS
(
food_id NUMBER PRIMARY KEY,
name VARCHAR NOT NULL,
price NUMBER(10,2) NOT NULL,
category VARCHAR NOT NULL,
availability VARCHAR NOT NULL
);

CREATE TABLE ORDERS
(
order_id NUMBER PRIMARY KEY,
customer_id NUMBER NOT NULL,
food_id NUMBER NOT NULL,
quantity NUMBER NOT NULL CHECK (quantity>0),
order_date TIMESTAMP NOT NULL,
status VARCHAR NOT NULL CHECK (status IN ('Pending','Delivered','Preparing','Cancelled')),
total_amount NUMBER(10,2) NOT NULL,
FOREIGN KEY(customer_id) REFERENCES CUSTOMERS(customer_id),
FOREIGN KEY(food_id) REFERENCES FOODITEMS(food_id)
);

-- INSERTING VALIDATED DATA
INSERT INTO CUSTOMERS
SELECT CUSTOMER_ID,
        FIRST_NAME,
        LAST_NAME,
        EMAIL,
        PHONE,
        ADDRESS
FROM RAW_CUSTOMERS
WHERE CUSTOMER_ID IS NOT NULL      
AND FIRST_NAME IS NOT NULL 
AND EMAIL IS NOT NULL 
AND PHONE IS NOT NULL;

INSERT INTO FOODITEMS
SELECT FOOD_ID,
        NAME,
        PRICE,
        CATEGORY,
        AVAILABILITY
FROM RAW_FOODITEMS
WHERE FOOD_ID IS NOT NULL 
AND NAME IS NOT NULL
AND PRICE IS NOT NULL
AND CATEGORY IS NOT NULL
AND AVAILABILITY IS NOT NULL 
AND AVAILABILITY IN ('Available','Unavailable');

INSERT INTO ORDERS
SELECT R_ORD.ORDER_ID,
       R_ORD.CUSTOMER_ID,
       R_ORD.FOOD_ID,
       R_ORD.QUANTITY,
       R_ORD.ORDER_DATE,
       R_ORD.STATUS,
       R_ORD.TOTAL_AMOUNT
FROM RAW_ORDERS R_ORD
INNER JOIN CUSTOMERS CUS
       ON R_ORD.CUSTOMER_ID=CUS.CUSTOMER_ID
INNER JOIN FOODITEMS FD
       ON R_ORD.FOOD_ID=FD.FOOD_ID
WHERE R_ORD.ORDER_ID IS NOT NULL AND
      R_ORD.CUSTOMER_ID IS NOT NULL AND
      R_ORD.FOOD_ID IS NOT NULL AND
      R_ORD.QUANTITY>0 AND
      R_ORD.ORDER_DATE IS NOT NULL AND
      R_ORD.STATUS IN ('Pending','Preparing','Delivered','Cancelled') AND
      R_ORD.TOTAL_AMOUNT IS NOT NULL ;


-- TASK 11
SELECT * FROM CUSTOMERS;


-- TASK 12
SELECT * FROM FOODITEMS;

-- TASK 13
SELECT * FROM ORDERS;

-- TASK 14
SELECT C.CUSTOMER_ID,CONCAT(C.FIRST_NAME,' ',C.LAST_NAME) AS CUSTOMER_NAME,SUM(O.TOTAL_AMOUNT) AS TOTAL_AMOUNT_SPENT
FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID,CONCAT(C.FIRST_NAME,' ',C.LAST_NAME);

-- TASK 15
SELECT C.CUSTOMER_ID,CONCAT(C.FIRST_NAME,' ',C.LAST_NAME) AS CUSTOMER_NAME,SUM(O.TOTAL_AMOUNT) AS TOTAL_AMOUNT_SPENT
FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID,CONCAT(C.FIRST_NAME,' ',C.LAST_NAME)
ORDER BY TOTAL_AMOUNT_SPENT DESC
LIMIT 1;

-- TASK 16
SELECT SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM ORDERS;

-- TASK 17
SELECT F.CATEGORY,SUM(O.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FOODITEMS F
INNER JOIN ORDERS O
ON F.FOOD_ID=O.FOOD_ID
GROUP BY F.CATEGORY;

-- TASK 18
SELECT STATUS,SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM ORDERS
GROUP BY STATUS;

-- TASK 19
SELECT C.CUSTOMER_ID,CONCAT(C.FIRST_NAME,' ',C.LAST_NAME) AS CUSTOMER_NAME,SUM(O.TOTAL_AMOUNT) AS TOTAL_AMOUNT_SPENT, DENSE_RANK() OVER(ORDER BY SUM(O.TOTAL_AMOUNT) DESC ) AS SPENT_RANK
FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID,C.FIRST_NAME,C.LAST_NAME
QUALIFY SPENT_RANK<=3;

-- SQL VERSION
SELECT CUSTOMER_ID,CUSTOMER_NAME,TOTAL_AMOUNT_SPENT
FROM (SELECT C.CUSTOMER_ID,
             CONCAT(C.FIRST_NAME,' ',C.LAST_NAME) AS CUSTOMER_NAME,
             SUM(O.TOTAL_AMOUNT) AS TOTAL_AMOUNT_SPENT, 
             DENSE_RANK() OVER(ORDER BY SUM(O.TOTAL_AMOUNT) DESC ) AS SPENT_RANK
      FROM CUSTOMERS C
      INNER JOIN ORDERS O
      ON C.CUSTOMER_ID=O.CUSTOMER_ID
      GROUP BY C.CUSTOMER_ID,C.FIRST_NAME,C.LAST_NAME) T
WHERE SPENT_RANK<=3;

-- TASK 20
SELECT C.CUSTOMER_ID,
       CONCAT(C.FIRST_NAME,' ',C.LAST_NAME) AS CUSTOMER_NAME,
       COUNT(O.ORDER_ID) AS NUMBER_OF_ORDERS_PLACED
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID,CONCAT(C.FIRST_NAME,' ',C.LAST_NAME)
ORDER BY NUMBER_OF_ORDERS_PLACED DESC;

-- TASK 21
SELECT * 
FROM ORDERS
WHERE STATUS='Delivered';

-- TASK 22
SELECT *
FROM ORDERS
WHERE ORDER_DATE>'2026-07-12';

-- TASK 23
CREATE VIEW CUSTOMER_SALES_REPORT AS
SELECT C.CUSTOMER_ID,
       CONCAT(C.FIRST_NAME,' ',C.LAST_NAME) AS CUSTOMER_NAME,
       SUM(O.TOTAL_AMOUNT) AS TOTAL_AMOUNT_SPENT
FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID,CONCAT(C.FIRST_NAME,' ',C.LAST_NAME);

-- TASK 24
SELECT * FROM CUSTOMER_SALES_REPORT;

-- TASK 25
SELECT * FROM CUSTOMER_SALES_REPORT
ORDER BY TOTAL_AMOUNT_SPENT DESC;


