USE WAREHOUSE ENTERPRISE_WH;

CREATE DATABASE LOGISTICS_LAKEHOUSE_DB;

USE DATABASE LOGISTICS_LAKEHOUSE_DB;

CREATE SCHEMA FLEET_CORE;

USE SCHEMA FLEET_CORE;

CREATE FILE FORMAT JSON_FORMAT
TYPE='JSON';

CREATE STAGE RAW_JSON_STAGE
FILE_FORMAT = JSON_FORMAT;

CREATE TABLE BRONZE_IOT_STREAMS
(
INGEST_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1 ,
RAW_PAYLOAD VARIANT,
RECORDED_AT TIMESTAMP
);

COPY INTO BRONZE_IOT_STREAMS(RAW_PAYLOAD,RECORDED_AT)
FROM 
(
SELECT  $1,
        CURRENT_TIMESTAMP()
FROM @RAW_JSON_STAGE/batch1_payloads.json
);

COPY INTO BRONZE_IOT_STREAMS(RAW_PAYLOAD,RECORDED_AT)
FROM 
(
SELECT  $1,
        CURRENT_TIMESTAMP()
FROM @RAW_JSON_STAGE/batch2_payloads.json
);

COPY INTO BRONZE_IOT_STREAMS(RAW_PAYLOAD,RECORDED_AT)
FROM 
(
SELECT  $1,
        CURRENT_TIMESTAMP()
FROM @RAW_JSON_STAGE/batch3_payloads.json
) ON_ERROR = CONTINUE;

SELECT COUNT(*) AS TOTAL_BRONZE_RECORDS
FROM BRONZE_IOT_STREAMS;

SELECT RAW_PAYLOAD FROM BRONZE_IOT_STREAMS;

SELECT  RAW_PAYLOAD:payload_id::VARCHAR(20) AS PAYLOAD_ID,
        RAW_PAYLOAD:payload_type::VARCHAR(20) AS PAYLOAD_TYPE,
        RAW_PAYLOAD:timestamp::TIMESTAMP AS TIMESTAMP,
        RAW_PAYLOAD:data.vehicle_id::VARCHAR(20) AS VEHICLE_ID,
        RAW_PAYLOAD:data.shipment_id::VARCHAR(20) AS SHIPMENT_ID,
        RAW_PAYLOAD:data.declared_value::NUMBER(10,2) AS DECLARED_VALUE
FROM BRONZE_IOT_STREAMS;


CREATE TABLE QUARANTINE_IOT_PAYLOADS
(
QUARANTINE_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
RAW_RECORD_TEXT VARCHAR(50),
REASON VARCHAR(50)
);
CREATE OR REPLACE FILE FORMAT RAW_TEXT_FORMAT
TYPE='CSV'
FIELD_DELIMITER=NONE
RECORD_DELIMITER='\n';

INSERT INTO QUARANTINE_IOT_PAYLOADS(RAW_RECORD_TEXT,REASON)
SELECT $1,'MALFORMED_JSON_BODY'
FROM @RAW_JSON_STAGE/batch3_payloads.json
(
FILE_FORMAT => RAW_TEXT_FORMAT
)
WHERE TRY_PARSE_JSON($1) IS NULL;

SELECT  QUARANTINE_ID,
        RAW_RECORD_TEXT,
        REASON
FROM QUARANTINE_IOT_PAYLOADS;


CREATE OR REPLACE TABLE SILVER_CUSTOMS_CLEARANCE
(
SHIPMENT_ID VARCHAR(20),
PAYLOAD_ID VARCHAR(20),
VEHICLE_ID VARCHAR(20),
DESTINATION_COUNTRY VARCHAR(20),
DECLARED_VALUE  NUMBER(10,2),
DUTY_PCT NUMBER(10,1),
DUTY_AMOUNT_DUE NUMBER(10,2),
BORDER_CODE VARCHAR(20),
CLEARANCE_STATUS VARCHAR(20)
);


INSERT INTO SILVER_CUSTOMS_CLEARANCE(SHIPMENT_ID,
                                     PAYLOAD_ID,
                                     VEHICLE_ID,
                                     DESTINATION_COUNTRY,
                                     DECLARED_VALUE,
                                     DUTY_PCT,
                                     DUTY_AMOUNT_DUE,
                                     BORDER_CODE,
                                     CLEARANCE_STATUS)
WITH SILVER_CTE AS
(
SELECT  RAW_PAYLOAD:data.shipment_id::VARCHAR(20) AS SHIPMENT_ID,
        RAW_PAYLOAD:payload_id::VARCHAR(20) AS PAYLOAD_ID,
        RAW_PAYLOAD:data.vehicle_id::VARCHAR(20) AS VEHICLE_ID,
        RAW_PAYLOAD:data.destination_country::VARCHAR(20) AS DESTINATION_COUNTRY,
        RAW_PAYLOAD:data.declared_value::NUMBER(10,2) AS DECLARED_VALUE,
        RAW_PAYLOAD:data.duty_pct::NUMBER(10,1) AS DUTY_PCT,
        RAW_PAYLOAD:data.border_clearance_code::VARCHAR(20) AS BORDER_CODE,
        RAW_PAYLOAD:data.clearance_status::VARCHAR(20) AS CLEARANCE_STATUS
FROM BRONZE_IOT_STREAMS
WHERE RAW_PAYLOAD:payload_type::VARCHAR(20) = 'CUSTOMS'
)
SELECT  SHIPMENT_ID,
        PAYLOAD_ID,
        VEHICLE_ID,
        DESTINATION_COUNTRY,
        DECLARED_VALUE,
        DUTY_PCT,
        ROUND(((DECLARED_VALUE*DUTY_PCT)/100),2) AS DUTY_AMOUNT_DUE,
        BORDER_CODE,
        CLEARANCE_STATUS
FROM SILVER_CTE;


SELECT  SHIPMENT_ID,
        VEHICLE_ID,
        DESTINATION_COUNTRY AS DEST_COUNTRY,
        DECLARED_VALUE,
        DUTY_PCT,
        DUTY_AMOUNT_DUE,
        BORDER_CODE,
        CLEARANCE_STATUS
FROM SILVER_CUSTOMS_CLEARANCE;


CREATE TABLE GOLD_COUNTRY_DUTY_SUMMARY
(
DEST_COUNTRY VARCHAR(20),
TOTAL_CLEARED_VAL NUMBER(12,2),
TOTAL_DUTIES_COLLECTED NUMBER(10,2),
AVG_DUTY_RATE_PCT NUMBER(10,2),
CLEARED_SHIPMENTS NUMBER
);

INSERT INTO GOLD_COUNTRY_DUTY_SUMMARY(DEST_COUNTRY,TOTAL_CLEARED_VAL,TOTAL_DUTIES_COLLECTED,AVG_DUTY_RATE_PCT,CLEARED_SHIPMENTS)
SELECT  DESTINATION_COUNTRY AS DEST_COUNTRY,
        SUM(DECLARED_VALUE) AS TOTAL_CLEARED_VAL,
        SUM(DUTY_AMOUNT_DUE) AS TOTAL_DUTIES_COLLECTED,
        ROUND(AVG(DUTY_PCT),2) AS AVG_DUTY_RATE_PCT,
        COUNT(CLEARANCE_STATUS) AS CLEARED_SHIPMENTS
FROM SILVER_CUSTOMS_CLEARANCE
WHERE CLEARANCE_STATUS = 'CLEARED'
GROUP BY DESTINATION_COUNTRY;


SELECT  DEST_COUNTRY,
        TOTAL_CLEARED_VAL,
        TOTAL_DUTIES_COLLECTED,
        AVG_DUTY_RATE_PCT,
        CLEARED_SHIPMENTS
FROM GOLD_COUNTRY_DUTY_SUMMARY;

UPDATE SILVER_CUSTOMS_CLEARANCE
SET CLEARANCE_STATUS = 'REJECTED'
WHERE DESTINATION_COUNTRY = 'CAN';

SELECT DESTINATION_COUNTRY,CLEARANCE_STATUS
FROM SILVER_CUSTOMS_CLEARANCE
BEFORE (STATEMENT => '01c698d5-3203-330d-0017-d5ea0017db92')
WHERE DESTINATION_COUNTRY = 'CAN';

SELECT DESTINATION_COUNTRY,CLEARANCE_STATUS
FROM SILVER_CUSTOMS_CLEARANCE
WHERE DESTINATION_COUNTRY = 'CAN';


UPDATE SILVER_CUSTOMS_CLEARANCE SLV
SET SLV.CLEARANCE_STATUS=OLD_SLV.CLEARANCE_STATUS
FROM (
SELECT CLEARANCE_STATUS
FROM SILVER_CUSTOMS_CLEARANCE
BEFORE (STATEMENT => '01c698d5-3203-330d-0017-d5ea0017db92')
WHERE DESTINATION_COUNTRY = 'CAN'
) OLD_SLV
WHERE SLV.DESTINATION_COUNTRY='CAN';

SELECT  DESTINATION_COUNTRY,
        COUNT_IF(CLEARANCE_STATUS='CLEARED') AS CLEARED_COUNT,
        COUNT_IF(CLEARANCE_STATUS='REJECTED') AS REJECTED_COUNT
FROM SILVER_CUSTOMS_CLEARANCE
GROUP BY DESTINATION_COUNTRY
ORDER BY DESTINATION_COUNTRY;

WITH BRONZE_TOTAL AS
(
SELECT SUM(RAW_PAYLOAD:data.declared_value::NUMBER(10,2)) AS BRONZE_GROSS_TOTAL
FROM BRONZE_IOT_STREAMS
), SILVER_TOTAL AS
(
SELECT SUM(DECLARED_VALUE) AS SILVER_GROSS_TOTAL
FROM SILVER_CUSTOMS_CLEARANCE
), GOLD_TOTAL AS
(
SELECT SUM(TOTAL_CLEARED_VAL) AS GOLD_GROSS_TOTAL
FROM GOLD_COUNTRY_DUTY_SUMMARY
)
SELECT  BRONZE_GROSS_TOTAL,
        SILVER_GROSS_TOTAL,
        GOLD_GROSS_TOTAL,
        CASE 
            WHEN BRONZE_GROSS_TOTAL=SILVER_GROSS_TOTAL
            THEN TRUE
            ELSE FALSE
        END AS RECONCILED_FLAG
FROM BRONZE_TOTAL,SILVER_TOTAL,GOLD_TOTAL;
        
