USE WAREHOUSE HEALTHCARE_WH;

CREATE DATABASE HEALTHCARE_DW;

USE DATABASE HEALTHCARE_DW; 

CREATE SCHEMA SCHEMA_COMPARE_LAB;

USE SCHEMA SCHEMA_COMPARE_LAB;

CREATE FILE FORMAT CSV_FORMAT 
TYPE='CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1;

CREATE STAGE RAW_STAGE
FILE_FORMAT = CSV_FORMAT;

CREATE TABLE STAR_DIM_HOSPITAL
(
HOSPITAL_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
HOSPITAL_ID NUMBER,
HOSPITAL_NAME VARCHAR,
CITY VARCHAR,
STATE VARCHAR,
NETWORK_NAME VARCHAR,
NETWORK_DIRECTOR VARCHAR
);

CREATE TABLE STAR_DIM_TREATMENT
(
TREATMENT_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
TREATMENT_ID NUMBER,
TREATMENT_NAME VARCHAR,
DIAGNOSIS_GROUP_NAME VARCHAR,
STANDARD_COST NUMBER(12,2)
);

INSERT INTO STAR_DIM_HOSPITAL(HOSPITAL_ID,HOSPITAL_NAME,CITY,STATE,NETWORK_NAME,NETWORK_DIRECTOR)
SELECT  $1,
        $2,
        $3,
        $4,
        $6,
        $7
FROM @RAW_STAGE/hospitals.csv;


INSERT INTO STAR_DIM_TREATMENT(TREATMENT_ID,TREATMENT_NAME,DIAGNOSIS_GROUP_NAME,STANDARD_COST)
SELECT  $1,
        $2,
        $4,
        $5
FROM @RAW_STAGE/treatments.csv;


CREATE OR REPLACE TABLE STAR_FACT_CLAIMS
(
CLAIM_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
CLAIM_ID VARCHAR,
CLAIM_DATE DATE,
PATIENT_ID NUMBER,
HOSPITAL_KEY NUMBER REFERENCES STAR_DIM_HOSPITAL(HOSPITAL_KEY),
TREATMENT_KEY NUMBER REFERENCES STAR_DIM_TREATMENT(TREATMENT_KEY),
CLAIMED_AMOUNT NUMBER(12,2),
APPROVED_AMOUNT NUMBER(12,2)
);


INSERT INTO STAR_FACT_CLAIMS(CLAIM_ID,CLAIM_DATE,PATIENT_ID,HOSPITAL_KEY,TREATMENT_KEY,CLAIMED_AMOUNT,APPROVED_AMOUNT)
SELECT  CLM.$1,
        CLM.$2,
        CLM.$3,
        HOS.HOSPITAL_KEY,
        TRT.TREATMENT_KEY,
        CLM.$6,
        CLM.$7
FROM @RAW_STAGE/insurance_claims.csv AS CLM
INNER JOIN STAR_DIM_HOSPITAL HOS
ON CLM.$4=HOS.HOSPITAL_ID
INNER JOIN STAR_DIM_TREATMENT TRT
ON CLM.$5=TRT.TREATMENT_ID;


CREATE TABLE SNOW_DIM_NETWORK
(
NETWORK_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
NETWORK_ID NUMBER,
NETWORK_NAME VARCHAR,
NETWORK_DIRECTOR VARCHAR
);

CREATE TABLE SNOW_DIM_HOSPITAL
(
HOSPITAL_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
HOSPITAL_ID NUMBER,
HOSPITAL_NAME VARCHAR,
CITY VARCHAR,
STATE VARCHAR,
NETWORK_KEY NUMBER REFERENCES SNOW_DIM_NETWORK(NETWORK_KEY)
);


CREATE TABLE SNOW_DIM_DIAGNOSIS_GROUP
(
DIAGNOSIS_GROUP_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
DIAGNOSIS_GROUP_ID VARCHAR,
DIAGNOSIS_GROUP_NAME VARCHAR
);


CREATE TABLE SNOW_DIM_TREATMENT
(
TREATMENT_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
TREATMENT_ID NUMBER,
TREATMENT_NAME VARCHAR,
STANDARD_COST NUMBER(12,2),
DIAGNOSIS_GROUP_KEY NUMBER
);


INSERT INTO SNOW_DIM_NETWORK(NETWORK_ID,NETWORK_NAME,NETWORK_DIRECTOR)
SELECT  DISTINCT $5,
        $6,
        $7
FROM @RAW_STAGE/hospitals.csv;


INSERT INTO SNOW_DIM_HOSPITAL(HOSPITAL_ID,HOSPITAL_NAME,CITY,STATE,NETWORK_KEY)
SELECT  HOS.$1,
        HOS.$2,
        HOS.$3,
        HOS.$4,
        NET.NETWORK_KEY
FROM @RAW_STAGE/hospitals.csv AS HOS
INNER JOIN SNOW_DIM_NETWORK NET
ON HOS.$5=NET.NETWORK_ID;

INSERT INTO SNOW_DIM_DIAGNOSIS_GROUP(DIAGNOSIS_GROUP_ID,DIAGNOSIS_GROUP_NAME)
SELECT  DISTINCT $3,
        $4
FROM @RAW_STAGE/treatments.csv;

INSERT INTO SNOW_DIM_TREATMENT(TREATMENT_ID,TREATMENT_NAME,STANDARD_COST,DIAGNOSIS_GROUP_KEY)
SELECT  TRT.$1,
        TRT.$2,
        TRT.$5,
        DIA.DIAGNOSIS_GROUP_KEY
FROM @RAW_STAGE/treatments.csv AS TRT
INNER JOIN SNOW_DIM_DIAGNOSIS_GROUP AS DIA
ON TRT.$3=DIA.DIAGNOSIS_GROUP_ID;


CREATE TABLE SNOW_FACT_CLAIMS
(
CLAIM_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
CLAIM_ID VARCHAR,
CLAIM_DATE DATE,
PATIENT_ID NUMBER,
HOSPITAL_KEY NUMBER REFERENCES SNOW_DIM_HOSPITAL(HOSPITAL_KEY),
TREATMENT_KEY NUMBER REFERENCES SNOW_DIM_TREATMENT(TREATMENT_KEY),
CLAIMED_AMOUNT NUMBER(12,2),
APPROVED_AMOUNT NUMBER(12,2)
);


INSERT INTO SNOW_FACT_CLAIMS(CLAIM_ID,CLAIM_DATE,PATIENT_ID,HOSPITAL_KEY,TREATMENT_KEY,CLAIMED_AMOUNT,APPROVED_AMOUNT)
SELECT  CLM.$1,
        CLM.$2,
        CLM.$3,
        HOS.HOSPITAL_KEY,
        TRT.TREATMENT_KEY,
        CLM.$6,
        CLM.$7
FROM @RAW_STAGE/insurance_claims.csv AS CLM
INNER JOIN SNOW_DIM_HOSPITAL HOS
ON CLM.$4=HOS.HOSPITAL_ID
INNER JOIN SNOW_DIM_TREATMENT TRT
ON CLM.$5=TRT.TREATMENT_ID;


SELECT  TRT.DIAGNOSIS_GROUP_NAME,
        SUM(CLM.CLAIMED_AMOUNT) AS TOTAL_CLAIMED_AMOUNT,
        SUM(CLM.APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT
FROM STAR_DIM_TREATMENT TRT
INNER JOIN STAR_FACT_CLAIMS CLM
ON TRT.TREATMENT_KEY=CLM.TREATMENT_KEY
GROUP BY TRT.DIAGNOSIS_GROUP_NAME
ORDER BY DIAGNOSIS_GROUP_NAME;


SELECT  DIA.DIAGNOSIS_GROUP_NAME,
        SUM(CLM.CLAIMED_AMOUNT) AS TOTAL_CLAIMED_AMOUNT,
        SUM(CLM.APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT
FROM SNOW_FACT_CLAIMS CLM
INNER JOIN SNOW_DIM_TREATMENT TRT 
ON CLM.TREATMENT_KEY=TRT.TREATMENT_KEY
INNER JOIN SNOW_DIM_DIAGNOSIS_GROUP DIA
ON TRT.DIAGNOSIS_GROUP_KEY=DIA.DIAGNOSIS_GROUP_KEY
GROUP BY DIA.DIAGNOSIS_GROUP_NAME
ORDER BY DIAGNOSIS_GROUP_NAME;


SELECT  HOS.NETWORK_DIRECTOR,
        COUNT(CLM.CLAIM_ID) AS TOTAL_CLAIMS_HANDLED,
        SUM(CLM.APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT
FROM STAR_FACT_CLAIMS CLM
INNER JOIN STAR_DIM_HOSPITAL HOS
ON CLM.HOSPITAL_KEY=HOS.HOSPITAL_KEY
GROUP BY NETWORK_DIRECTOR;


SELECT  NET.NETWORK_DIRECTOR,
        COUNT(CLM.CLAIM_ID) AS TOTAL_CLAIMS_HANDLED,
        SUM(CLM.APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT
FROM SNOW_FACT_CLAIMS CLM
INNER JOIN SNOW_DIM_HOSPITAL HOS
ON CLM.HOSPITAL_KEY=HOS.HOSPITAL_KEY
INNER JOIN SNOW_DIM_NETWORK NET
ON HOS.NETWORK_KEY=NET.NETWORK_KEY
GROUP BY NET.NETWORK_DIRECTOR
ORDER BY TOTAL_CLAIMS_HANDLED DESC;


SELECT * FROM STAR_DIM_HOSPITAL;

SELECT * FROM SNOW_DIM_NETWORK;

UPDATE STAR_DIM_HOSPITAL
SET NETWORK_DIRECTOR  = 'Dr. Anand'
WHERE NETWORK_NAME = 'Apollo Healthcare Group';

UPDATE SNOW_DIM_NETWORK
SET NETWORK_DIRECTOR = 'Dr. Anand'
WHERE NETWORK_ID=10;


SELECT  'Star Schema' AS SCHEMA_TYPE,
        'STAR_DIM_HOSPITAL' AS TABLE_NAME,
        COUNT(*) AS RECORD_COUNT
FROM STAR_DIM_HOSPITAL
UNION ALL
SELECT  'Star Schema' AS SCHEMA_TYPE,
        'STAR_DIM_TREATMENT' AS TABLE_NAME,
        COUNT(*) AS RECORD_COUNT
FROM STAR_DIM_TREATMENT
UNION ALL
SELECT  'Star Schema' AS SCHEMA_TYPE,
        'STAR_FACT_CLAIMS' AS TABLE_NAME,
        COUNT(*) AS RECORD_COUNT
FROM STAR_FACT_CLAIMS
UNION ALL
SELECT  'Snowflake Schema' AS SCHEMA_TYPE,
        'SNOW_DIM_NETWORK' AS TABLE_NAME,
        COUNT(*) AS RECORD_COUNT
FROM SNOW_DIM_NETWORK
UNION ALL
SELECT  'Snowflake Schema' AS SCHEMA_TYPE,
        'SNOW_DIM_HOSPITAL' AS TABLE_NAME,
        COUNT(*) AS RECORD_COUNT
FROM SNOW_DIM_HOSPITAL
UNION ALL
SELECT  'Snowflake Schema' AS SCHEMA_TYPE,
        'SNOW_DIM_DIAGNOSIS_GROUP' AS TABLE_NAME,
        COUNT(*) AS RECORD_COUNT
FROM SNOW_DIM_DIAGNOSIS_GROUP
UNION ALL
SELECT  'Snowflake Schema' AS SCHEMA_TYPE,
        'SNOW_DIM_TREATMENT' AS TABLE_NAME,
        COUNT(*) AS RECORD_COUNT
FROM SNOW_DIM_TREATMENT
UNION ALL
SELECT  'Snowflake Schema' AS SCHEMA_TYPE,
        'SNOW_FACT_CLAIMS' AS TABLE_NAME,
        COUNT(*) AS RECORD_COUNT
FROM SNOW_FACT_CLAIMS;
