USE DATABASE HEALTHCARE_DB;

USE SCHEMA HEALTHCARE_SCHEMA;

CREATE OR REPLACE FILE FORMAT JSON_FORMAT
TYPE ='JSON';

CREATE OR REPLACE STAGE RAW_HEALTH_STAGE
FILE_FORMAT = JSON_FORMAT;

CREATE TABLE FACT_PATIENT_ENCOUNTERS
(
ENCOUNTER_ID VARCHAR(20),
PATIENT_ID VARCHAR(20),
ADMIT_DATE_KEY NUMBER,
DISCHARGE_DATE_KEY NUMBER,
BILLING_DATE_KEY NUMBER,
PRIMARY_DIAG_ID VARCHAR(20),
TOTAL_COST NUMBER(10,2)
);

LIST @RAW_HEALTH_STAGE;

INSERT INTO FACT_PATIENT_ENCOUNTERS(
                                    ENCOUNTER_ID,  
                                    PATIENT_ID,
                                    ADMIT_DATE_KEY,
                                    DISCHARGE_DATE_KEY,
                                    BILLING_DATE_KEY,
                                    PRIMARY_DIAG_ID,
                                    TOTAL_COST
)
SELECT  VALUE:encounter_id::VARCHAR(20),
        VALUE:patient_id::VARCHAR(20),
        VALUE:admit_date_key::NUMBER,
        VALUE:discharge_date_key::NUMBER,
        VALUE:billing_date_key::NUMBER,
        VALUE:primary_diag_id::VARCHAR(20),
        VALUE:total_cost::NUMBER(10,2)
FROM @RAW_HEALTH_STAGE/raw_encounters.json
(FILE_FORMAT => JSON_FORMAT ),
LATERAL FLATTEN(INPUT => $1);

SELECT * 
FROM FACT_PATIENT_ENCOUNTERS;

CREATE VIEW VW_ADMIT_DATE AS
SELECT  DISTINCT FPE.ADMIT_DATE_KEY,
        DD.FULL_DATE AS ADMIT_DATE
FROM (SELECT VALUE:date_key::NUMBER AS DATE_KEY,
             VALUE:full_date::DATE AS FULL_DATE
      FROM @RAW_HEALTH_STAGE/dim_date.json
      (FILE_FORMAT => JSON_FORMAT),
      LATERAL FLATTEN(INPUT => $1)
      ) DD
INNER JOIN FACT_PATIENT_ENCOUNTERS FPE
ON FPE.ADMIT_DATE_KEY=DD.DATE_KEY;

CREATE VIEW VW_DISCHARGE_DATE AS 
SELECT  DISTINCT FPE.DISCHARGE_DATE_KEY,
        DD.FULL_DATE AS DISCHARGE_DATE
FROM (SELECT VALUE:date_key::NUMBER AS DATE_KEY,
             VALUE:full_date::DATE AS FULL_DATE
      FROM @RAW_HEALTH_STAGE/dim_date.json
      (FILE_FORMAT => JSON_FORMAT),
      LATERAL FLATTEN(INPUT => $1)
      ) DD
INNER JOIN FACT_PATIENT_ENCOUNTERS FPE
ON FPE.DISCHARGE_DATE_KEY=DD.DATE_KEY;

CREATE VIEW VW_BILLING_DATE AS 
SELECT  DISTINCT FPE.BILLING_DATE_KEY,
        DD.FULL_DATE AS BILLING_DATE
FROM (SELECT VALUE:date_key::NUMBER AS DATE_KEY,
             VALUE:full_date::DATE AS FULL_DATE
      FROM @RAW_HEALTH_STAGE/dim_date.json
      (FILE_FORMAT => JSON_FORMAT),
      LATERAL FLATTEN(INPUT => $1)
      ) DD
INNER JOIN FACT_PATIENT_ENCOUNTERS FPE
ON FPE.BILLING_DATE_KEY=DD.DATE_KEY;

SELECT  FPE.ENCOUNTER_ID,
        AD.ADMIT_DATE,
        DD.DISCHARGE_DATE,
        BD.BILLING_DATE
FROM FACT_PATIENT_ENCOUNTERS FPE
INNER JOIN VW_ADMIT_DATE AD
ON FPE.ADMIT_DATE_KEY=AD.ADMIT_DATE_KEY
INNER JOIN VW_DISCHARGE_DATE DD
ON FPE.DISCHARGE_DATE_KEY=DD.DISCHARGE_DATE_KEY
INNER JOIN VW_BILLING_DATE BD
ON FPE.BILLING_DATE_KEY=BD.BILLING_DATE_KEY
ORDER BY ENCOUNTER_ID
LIMIT 3;


SELECT  BD.ENCOUNTER_ID,
        BD.DOCTOR_ID,
        BD.WEIGHT_FACTOR,
        ROUND(FPE.TOTAL_COST*BD.WEIGHT_FACTOR,2) AS ATTRIBUTED_COST
FROM (SELECT  VALUE:encounter_id::VARCHAR(20) AS ENCOUNTER_ID,
              VALUE:doctor_id::VARCHAR(20) AS DOCTOR_ID,
              VALUE:weight_factor::NUMBER(10,2) AS WEIGHT_FACTOR
      FROM @RAW_HEALTH_STAGE/bridge_doctors.json,
      LATERAL FLATTEN(INPUT => $1)
      ) BD
INNER JOIN FACT_PATIENT_ENCOUNTERS FPE
ON FPE.ENCOUNTER_ID=BD.ENCOUNTER_ID;


WITH RECURSIVE DIAGNOSIS_PATH AS
(
SELECT  VALUE:diagnosis_id::VARCHAR(20) AS DIAGNOSIS_ID,
        VALUE:diagnosis_name::VARCHAR(50) AS DIAGNOSIS_NAME,
        VALUE:parent_diagnosis_id::VARCHAR(20) AS PARENT_DIAG_ID,
        VALUE:category_level::NUMBER AS CATEGORY_LEVEL,
        VALUE:diagnosis_name::VARCHAR(50) AS ROOT_CATEGORY_NAME
FROM @RAW_HEALTH_STAGE/dim_diagnosis.json,
LATERAL FLATTEN(INPUT => $1)
WHERE VALUE:category_level::NUMBER =1
UNION ALL 
SELECT  DIA.VALUE:diagnosis_id::VARCHAR(20) AS DIAGNOSIS_ID,
        DIA.VALUE:diagnosis_name::VARCHAR(50) AS DIAGNOSIS_NAME,
        DIA.VALUE:parent_diagnosis_id::VARCHAR(20) AS PARENT_DIAG_ID,
        DIA.VALUE:category_level::NUMBER AS CATEGORY_LEVEL,
        DP.ROOT_CATEGORY_NAME
FROM @RAW_HEALTH_STAGE/dim_diagnosis.json ,
LATERAL FLATTEN(INPUT => $1) DIA
INNER JOIN DIAGNOSIS_PATH DP
ON DP.DIAGNOSIS_ID = DIA.VALUE:parent_diagnosis_id::VARCHAR(20)
)
SELECT  DIAGNOSIS_ID,
        DIAGNOSIS_NAME,
        ROOT_CATEGORY_NAME
FROM DIAGNOSIS_PATH
ORDER BY DIAGNOSIS_ID;


CREATE OR REPLACE TEMPORARY TABLE INCOMING_DATA AS
SELECT  'ENC-801' AS ENCOUNTER_ID,
        'PAT-10' AS PATIENT_ID,
        20260801 AS ADMIT_DATE_KEY,
        20260804 AS DISCHARGE_DATE_KEY,
        20260806 AS BILLING_DATE_KEY,
        'ICD-1110' AS PRIMARY_DIAG_ID,
        5000.00 AS TOTAL_COST
UNION ALL
SELECT  'ENC-821',
        'PAT-30',
        20260816,
        20260821,
        20260825,
        'ICD-3110',
        7000.00;

SELECT * FROM INCOMING_DATA;

MERGE INTO FACT_PATIENT_ENCOUNTERS T
USING INCOMING_DATA S
ON T.ENCOUNTER_ID = S.ENCOUNTER_ID
WHEN MATCHED THEN
    UPDATE SET
        T.PATIENT_ID=S.PATIENT_ID,
        T.ADMIT_DATE_KEY=S.ADMIT_DATE_KEY,
        T.DISCHARGE_DATE_KEY = S.DISCHARGE_DATE_KEY,
        T.BILLING_DATE_KEY=S.BILLING_DATE_KEY,
        T.PRIMARY_DIAG_ID=S.PRIMARY_DIAG_ID,
        T.TOTAL_COST=S.TOTAL_COST
WHEN NOT MATCHED THEN
    INSERT(ENCOUNTER_ID,
           PATIENT_ID,
           ADMIT_DATE_KEY,
           DISCHARGE_DATE_KEY,
           BILLING_DATE_KEY,
           PRIMARY_DIAG_ID,
           TOTAL_COST)
    VALUES(S.ENCOUNTER_ID,
           S.PATIENT_ID,
           S.ADMIT_DATE_KEY,
           S.DISCHARGE_DATE_KEY,
           S.BILLING_DATE_KEY,
           S.PRIMARY_DIAG_ID,
           S.TOTAL_COST);

SELECT * 
FROM FACT_PATIENT_ENCOUNTERS
WHERE ENCOUNTER_ID = 'ENC-801';

SELECT * 
FROM FACT_PATIENT_ENCOUNTERS
BEFORE(STATEMENT => '01c6bc0e-3203-3f20-0017-d5ea00260e02')
WHERE ENCOUNTER_ID = 'ENC-801';

ALTER TABLE FACT_PATIENT_ENCOUNTERS
ADD COLUMN PATIENT_FEEDBACK_SCORE NUMBER(5,2);

DESC TABLE FACT_PATIENT_ENCOUNTERS;

SELECT  COUNT(*) AS TOTAL_ROWS,
        COUNT(PATIENT_FEEDBACK_SCORE) AS FEEDBACK_ROWS
FROM FACT_PATIENT_ENCOUNTERS;

ALTER TABLE FACT_PATIENT_ENCOUNTERS
CLUSTER BY (PATIENT_ID,PRIMARY_DIAG_ID);

SHOW TABLES LIKE 'FACT_PATIENT_ENCOUNTERS';

SELECT  TABLE_NAME,
        CLUSTERING_KEY
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME='FACT_PATIENT_ENCOUNTERS';