USE DATABASE ENTERPRISE_DB;

CREATE SCHEMA ENTERPRISE_SCHEMA;

USE SCHEMA ENTERPRISE_SCHEMA;

CREATE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1;

CREATE STAGE RAW_STAGE
FILE_FORMAT = CSV_FORMAT;

CREATE TABLE DIM_WIRE_ATTRIBUTES
(
ATTRIBUTE_SK NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
AUTH_METHOD VARCHAR(20),
RISK_FLAG VARCHAR(20),
TRANSFER_TYPE VARCHAR(20)
);

INSERT INTO DIM_WIRE_ATTRIBUTES(AUTH_METHOD,RISK_FLAG,TRANSFER_TYPE)
SELECT  DISTINCT $8 AS AUTH_METHOD,
        $9 AS RISK_FLAG,
        $10 AS TRANSFER_TYPE
FROM @RAW_STAGE/raw_wire_transfers.csv
ORDER BY TRANSFER_TYPE;

SELECT * 
FROM DIM_WIRE_ATTRIBUTES
ORDER BY ATTRIBUTE_SK;

CREATE OR REPLACE TABLE FACT_WIRE_TRANSFERS
(
TXN_ID VARCHAR(20),
TXN_DATE DATE,
SENDER_ACC VARCHAR(20),
RECEIVER_ACC VARCHAR(20),
ATTRIBUTE_SK NUMBER REFERENCES DIM_WIRE_ATTRIBUTES(ATTRIBUTE_SK),
AMOUNT NUMBER(10,2),
FEE NUMBER(10,2),
BASE_VAL_USD NUMBER(10,2),
NET_TRANSFER_VAL NUMBER(10,2)
);

INSERT INTO FACT_WIRE_TRANSFERS(TXN_ID,TXN_DATE,SENDER_ACC,RECEIVER_ACC,ATTRIBUTE_SK,AMOUNT,FEE,BASE_VAL_USD,NET_TRANSFER_VAL)
SELECT  RAW.$1 AS TXN_ID,
        RAW.$2 AS TXN_DATE,
        RAW.$3 AS SENDER_ACC,
        RAW.$4 AS RECEIVER_ACC,
        DIM.ATTRIBUTE_SK AS ATTRIBUTE_SK,
        RAW.$5 AS AMOUNT,
        RAW.$6 AS FEE,
        (RAW.$5*RAW.$7) AS BASE_VAL,
        (RAW.$5*RAW.$7)-RAW.$6 AS NET_TRANSFER_VAL
FROM @RAW_STAGE/raw_wire_transfers.csv RAW
INNER JOIN DIM_WIRE_ATTRIBUTES DIM
ON RAW.$8=DIM.AUTH_METHOD AND RAW.$9=DIM.RISK_FLAG AND RAW.$10=DIM.TRANSFER_TYPE
ORDER BY TXN_ID;
        

SELECT * 
FROM FACT_WIRE_TRANSFERS;

CREATE OR REPLACE TABLE FACT_VAULT_CASH_SNAPSHOT
(
SNAPSHOT_DATE DATE,
TOTAL_OPENING_USD_EQU NUMBER(10,2),
TOTAL_CLOSING_USD_EQU NUMBER(10,2)
);

INSERT INTO FACT_VAULT_CASH_SNAPSHOT(SNAPSHOT_DATE,TOTAL_OPENING_USD_EQU,TOTAL_CLOSING_USD_EQU)
SELECT  $1 AS SNAPSHOT_DATE,
        SUM($4) AS TOTAL_OPENING_USD_EQU,
        SUM($5) AS TOTAL_CLOSING_USD_EQU
FROM @RAW_STAGE/raw_vault_cash.csv
GROUP BY $1;

SELECT * 
FROM FACT_VAULT_CASH_SNAPSHOT;

CREATE TABLE FACT_CREDIT_APPROVAL_LIFECYCLE
(
APP_ID VARCHAR(20),
SUBMISSION_DATE DATE,
UNDERWRITE_DATE DATE,
RISK_APPROVAL_DATE DATE,
DISBURSEMENT_DATE DATE,
UNDERWRITE_DAYS NUMBER,
RISK_APPROVAL_DAYS NUMBER,
DISBURSEMENT_DAYS NUMBER,
TOTAL_CYCLE_DAYS NUMBER
);

INSERT INTO FACT_CREDIT_APPROVAL_LIFECYCLE(APP_ID,
                                           SUBMISSION_DATE,
                                           UNDERWRITE_DATE,
                                           RISK_APPROVAL_DATE,
                                           DISBURSEMENT_DATE,
                                           UNDERWRITE_DAYS,
                                           RISK_APPROVAL_DAYS,
                                           DISBURSEMENT_DAYS,
                                           TOTAL_CYCLE_DAYS)
SELECT  $1 AS APP_ID,
        NULLIF($2,'NULL') AS SUBMISSION_DATE,
        NULLIF($3,'NULL') AS UNDERWRITE_DATE,
        NULLIF($4,'NULL') AS RISK_APPROVAL_DATE,
        NULLIF($5,'NULL') AS DISBURSEMENT_DATE,
        DATEDIFF('DAY',NULLIF($2,'NULL'),NULLIF($3,'NULL')) AS UNDERWRITE_DAYS,
        DATEDIFF('DAY',NULLIF($3,'NULL'),NULLIF($4,'NULL')) AS RISK_APPROVAL_DAYS,
        DATEDIFF('DAY',NULLIF($4,'NULL'),NULLIF($5,'NULL')) AS DISBURSEMENT_DAYS,
        DATEDIFF('DAY',NULLIF($2,'NULL'),NULLIF($5,'NULL')) AS TOTAL_CYCLE_DAYS
FROM @RAW_STAGE/raw_credit_lifecycles.csv;
        
SELECT  APP_ID,
        UNDERWRITE_DAYS,
        RISK_APPROVAL_DAYS,
        DISBURSEMENT_DAYS,
        TOTAL_CYCLE_DAYS
FROM FACT_CREDIT_APPROVAL_LIFECYCLE
WHERE TOTAL_CYCLE_DAYS IS NOT NULL;

SELECT  APP_ID,
        SUBMISSION_DATE,
        CASE 
            WHEN UNDERWRITE_DATE IS NULL
            THEN 'AWAITING UNDERWRITE'
            WHEN RISK_APPROVAL_DATE IS NULL
            THEN 'AWAITING RISK_AUTH'
            WHEN DISBURSEMENT_DATE IS NULL
            THEN 'AWAITING_DISBURSAL'
        END AS CURRENT_BOTTLENECK
FROM FACT_CREDIT_APPROVAL_LIFECYCLE
WHERE DISBURSEMENT_DATE IS NULL;

CREATE OR REPLACE TABLE FACTLESS_COMPLIANCE_AUDIT_COVERAGE
(
ACCOUNT_ID VARCHAR(20),
HIGH_RISK_TXN_COUNT NUMBER,
COMPLIANCE_STATUS VARCHAR(20)
);

INSERT INTO FACTLESS_COMPLIANCE_AUDIT_COVERAGE(ACCOUNT_ID,HIGH_RISK_TXN,COMPLIANCE_STATUS)
SELECT  FCT.SENDER_ACC AS ACCOUNT_ID,
        COUNT(*) AS HIGH_RISK_TXN,
        'AUDITED' AS COMPLIANCE_STATUS
FROM FACT_WIRE_TRANSFERS FCT
INNER JOIN DIM_WIRE_ATTRIBUTES DIM
ON DIM.ATTRIBUTE_SK=FCT.ATTRIBUTE_SK
LEFT JOIN @RAW_STAGE/raw_audit_coverage.csv RAW
ON RAW.$3=FCT.SENDER_ACC AND RAW.$1=2026
WHERE DIM.RISK_FLAG='HIGH' AND RAW.$3 IS NULL
GROUP BY FCT.SENDER_ACC;

SELECT  DIM.RISK_FLAG,
        DIM.TRANSFER_TYPE,
        COUNT(FCT.TXN_ID) AS TOTAL_TXNS,
        SUM(FCT.FEE) AS TOTAL_FEES,
        SUM(FCT.NET_TRANSFER_VAL) AS TOTAL_VOLUMN_USD
FROM DIM_WIRE_ATTRIBUTES DIM
INNER JOIN FACT_WIRE_TRANSFERS FCT
ON DIM.ATTRIBUTE_SK=FCT.ATTRIBUTE_SK
GROUP BY DIM.RISK_FLAG,DIM.TRANSFER_TYPE
ORDER BY DIM.RISK_FLAG;

WITH CTE1 AS
(
SELECT SUM(NET_TRANSFER_VAL) AS TOTAL_WIRE_VOL_USD
FROM FACT_WIRE_TRANSFERS
),CTE2 AS
(
SELECT TOTAL_CLOSING_USD_EQU AS VAULT_CLOSING_USD
FROM FACT_VAULT_CASH_SNAPSHOT
WHERE SNAPSHOT_DATE= (SELECT MAX(SNAPSHOT_DATE) FROM FACT_VAULT_CASH_SNAPSHOT)
),CTE3 AS
(
SELECT COUNT(APP_ID) AS COMPLETED_LOAN_APPS
FROM FACT_CREDIT_APPROVAL_LIFECYCLE
WHERE DISBURSEMENT_DATE IS NOT NULL
)
SELECT  TOTAL_WIRE_VOL_USD,
        VAULT_CLOSING_USD,
        COMPLETED_LOAN_APPS,
        TRUE AS AUDIT_SANITY_FLAG
FROM CTE1,CTE2,CTE3