CREATE DATABASE HEALTHCARE_PIPELINE_DB;

USE DATABASE HEALTHCARE_PIPELINE_DB;

CREATE SCHEMA CLAIMS_CORE;

USE SCHEMA CLAIMS_CORE;

CREATE TABLE BRONZE_RAW_CLAIMS
(
INGEST_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
RAW_PAYLOAD VARIANT,
LOADED_AT TIMESTAMP
);

CREATE FILE FORMAT JSON_FORMAT
TYPE = 'JSON';

CREATE STAGE RAW_JSON_STAGE
FILE_FORMAT = JSON_FORMAT;

COPY INTO  BRONZE_RAW_CLAIMS(RAW_PAYLOAD,LOADED_AT)
FROM 
(
SELECT  $1,
        CURRENT_TIMESTAMP()
FROM @RAW_JSON_STAGE/batch1_payloads.json
);

COPY INTO  BRONZE_RAW_CLAIMS(RAW_PAYLOAD,LOADED_AT)
FROM 
(
SELECT  $1,
        CURRENT_TIMESTAMP()
FROM @RAW_JSON_STAGE/batch2_payloads.json
);

COPY INTO  BRONZE_RAW_CLAIMS(RAW_PAYLOAD,LOADED_AT)
FROM 
(
SELECT  $1,
        CURRENT_TIMESTAMP()
FROM @RAW_JSON_STAGE/batch3_payloads.json
) ON_ERROR = CONTINUE;


SELECT  COUNT(*) AS TOTAL_BRONZE_RECORDS
FROM BRONZE_RAW_CLAIMS;


CREATE TABLE QUARANTINE_CLAIMS_PAYLOAD
(
QUARANTINE_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
RAW_RECORD_TEXT VARCHAR(100),
REASON VARCHAR(100)
);

CREATE FILE FORMAT RAW_TEXT_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = NONE
RECORD_DELIMITER = '\n';


INSERT INTO QUARANTINE_CLAIMS_PAYLOAD(RAW_RECORD_TEXT,REASON)
SELECT  $1,
        'MALFORMED_JSON_BODY' AS REASON
FROM @RAW_JSON_STAGE/batch3_payloads.json
(
FILE_FORMAT => RAW_TEXT_FORMAT
)
WHERE TRY_PARSE_JSON($1) IS NULL;


SELECT  QUARANTINE_ID,
        RAW_RECORD_TEXT,
        REASON
FROM QUARANTINE_CLAIMS_PAYLOAD;


CREATE STREAM STRM_BRONZE_CLAIMS
ON TABLE BRONZE_RAW_CLAIMS;

CREATE TABLE SILVER_CLAIMS_TRANSACTIONS
(
CLAIM_ID VARCHAR(20),
SUBMITTED_AT TIMESTAMP,
PATIENT_ID NUMBER,
PROVIDER_ID VARCHAR(20),
DIAGNOSIS_CODE VARCHAR(20),
BILLED_AMOUNT NUMBER(10,2),
COPAY_AMOUNT NUMBER(10,2),
NET_PAYABLE_AMOUNT NUMBER(12,2),
STATUS VARCHAR(20)
);


INSERT INTO SILVER_CLAIMS_TRANSACTIONS(CLAIM_ID,SUBMITTED_AT,PATIENT_ID,PROVIDER_ID,DIAGNOSIS_CODE,BILLED_AMOUNT,COPAY_AMOUNT,NET_PAYABLE_AMOUNT,STATUS)
WITH SILVER_CTE AS
(
SELECT  INGEST_ID,
        RAW_PAYLOAD:claim_id::VARCHAR(20) AS CLAIM_ID,
        RAW_PAYLOAD:submitted_at::TIMESTAMP AS SUBMITTED_AT,
        RAW_PAYLOAD:patient_id::NUMBER AS PATIENT_ID,
        RAW_PAYLOAD:provider_id::VARCHAR(20) AS PROVIDER_ID,
        RAW_PAYLOAD:diagnosis_code::VARCHAR(20) AS DIAGNOSIS_CODE,
        RAW_PAYLOAD:billed_amount::NUMBER AS BILLED_AMOUNT,
        RAW_PAYLOAD:copay_amount::NUMBER AS COPAY_AMOUNT,
        RAW_PAYLOAD:status::VARCHAR(20) AS STATUS,
        ROW_NUMBER() OVER (
        PARTITION BY RAW_PAYLOAD:claim_id::VARCHAR
        ORDER BY INGEST_ID DESC
        ) AS RN
FROM BRONZE_RAW_CLAIMS
)
SELECT  CLAIM_ID,
        SUBMITTED_AT,
        PATIENT_ID,
        PROVIDER_ID,
        DIAGNOSIS_CODE,
        BILLED_AMOUNT,
        COPAY_AMOUNT,
        (BILLED_AMOUNT-COPAY_AMOUNT) AS NET_PAYABLE_AMOUNT,
        STATUS
FROM SILVER_CTE
WHERE RN=1;


SELECT  CLAIM_ID,
        PATIENT_ID,
        PROVIDER_ID,
        DIAGNOSIS_CODE,
        BILLED_AMOUNT,
        COPAY_AMOUNT,
        NET_PAYABLE_AMOUNT,
        STATUS
FROM SILVER_CLAIMS_TRANSACTIONS;

CREATE DYNAMIC TABLE DT_PROVIDER_FINANCIAL_SUMMARY
TARGET_LAG='1 MINUTE'
WAREHOUSE = COMPUTE_WH
AS 
SELECT  PROVIDER_ID,
        SUM(BILLED_AMOUNT) AS TOTAL_BILLED_AMOUNT,
        SUM(COPAY_AMOUNT) AS TOTAL_COPAY_COLLECT,
        SUM(NET_PAYABLE_AMOUNT) AS TOTAL_NET_PAYABLE,
        COUNT(*) AS APPROVED_CLAIMS
FROM SILVER_CLAIMS_TRANSACTIONS
WHERE STATUS = 'APPROVED'
GROUP BY PROVIDER_ID;


SELECT * FROM DT_PROVIDER_FINANCIAL_SUMMARY;

SHOW DYNAMIC TABLES;

SELECT  *        
FROM TABLE(
    INFORMATION_SCHEMA.DYNAMIC_TABLE_REFRESH_HISTORY(
        NAME => 'DT_PROVIDER_FINANCIAL_SUMMARY'
    )
);

WITH BRONZE_TOTAL AS
(
SELECT  SUM(RAW_PAYLOAD:billed_amount::NUMBER(10,2)) AS BRONZE_GROSS_TOTAL
FROM BRONZE_RAW_CLAIMS
), SILVER_TOTAL AS
(
SELECT SUM(BILLED_AMOUNT) AS SILVER_GROSS_TOTAL
FROM SILVER_CLAIMS_TRANSACTIONS
), GOLD_TOTAL AS
(
SELECT SUM(TOTAL_BILLED_AMOUNT) AS GOLD_GROSS_TOTAL
FROM DT_PROVIDER_FINANCIAL_SUMMARY
)
SELECT  BRONZE_GROSS_TOTAL,
        SILVER_GROSS_TOTAL,
        GOLD_GROSS_TOTAL,
        CASE 
            WHEN BRONZE_GROSS_TOTAL>SILVER_GROSS_TOTAL AND SILVER_GROSS_TOTAL>GOLD_GROSS_TOTAL
            THEN TRUE
            ELSE FALSE
        END AS RECONCILED_FLAG
FROM BRONZE_TOTAL,SILVER_TOTAL,GOLD_TOTAL;

